oli2/api/urls.py
from api.views.configuracoes import *
from api.views.empresas import *
from api.views.pessoas import *
from api.views.pedidos import *
from api.views.usuarios import *
from api.views.relatorios import *
from api.views.produtos import *
from rest_framework import routers

router = routers.DefaultRouter()
router.register('configuracoes', ConfiguracoesViewSet, 'Configuracoes')
router.register('empresas', EmpresasViewSet, 'Empresas')
router.register('minha_empresa', MinhaEmpresaViewSet, 'MinhaEmpresa')
router.register('tipos_empresa', TiposEmpresaViewSet, 'TiposEmpresa')
router.register('clientes', ClientesViewSet, 'Clientes')
router.register('prepostos', PrepostosViewSet, 'Prepostos')
router.register('rotas', RotasViewSet, 'Rotas')
router.register('rotas_prepostos', RotasPrepostosViewSet, 'RotasPrepostos')
router.register('preposto_clientes', PrepostoClientesViewSet, 'PrepostoClientes')
router.register('contatos', ContatosViewSet, 'Contatos')
router.register('formas_pagamento', FormasPagamentoViewSet, 'FormasPagamento')
router.register('pedidos', PedidosViewSet, 'Pedidos')
router.register('itens_pedido', ItensPedidoViewSet, 'ItensPedido')
router.register('categorias', CategoriasViewSet, 'Categorias')
router.register('unidades_venda', UnidadesVendaViewSet, 'UnidadesVenda')
router.register('tipos_embalagem', TiposEmbalagemViewSet, 'TiposEmbalagem')
router.register('produtos', ProdutosViewSet, 'Produtos')
router.register('acompanhamentos', AcompanhamentosViewSet, 'Acompanhamentos')
router.register('acompanhamento_empresa', AcompanhamentoEmpresaViewSet, 'AcompanhamentoEmpresa')
router.register('acompanhamento_preposto_empresa', AcompanhamentoPrepostoEmpresaViewSet, 'AcompanhamentoPrepostoEmpresa')
router.register('usuarios', UsuariosViewSet, 'Usuarios')
router.register('tarefas', TarefasViewSet, 'Tarefas')

urlpatterns = router.urls

oli2/representacao/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .customizacoes_urls import urlpatterns as customizacoes_urls
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login', auth_views.LoginView.as_view(template_name='usuarios/login.html'), name='login'),
    path('autenticar', views.autenticar, name='autenticar'),
    path('logout', auth_views.LogoutView.as_view(template_name='usuarios/logout.html'), name='logout'),
    path('usuarios/', views.listar_usuarios, name='usuarios'),
    path('usuarios/cadastrar', views.cadastrar_usuario, name='cadastrar-usuario'),
    path('editar/usuario/<int:id_usuario>', views.editar_usuario, name='editar-usuario'),
    path('remover/usuario/<int:id_usuario>', views.excluir_usuario, name='excluir-usuario'),
    path('tipos-empresa/', views.listar_tipos_empresa, name='tipos-empresa'),
    path('tipos-empresa/cadastrar', views.cadastrar_tipo_empresa, name='cadastrar-tipo-empresa'),
    path('editar/tipo_empresa/<int:id_tipo_empresa>', views.editar_tipo_empresa, name='editar-tipo-empresa'),
    path('remover/tipo_empresa/<int:id_tipo_empresa>', views.excluir_tipo_empresa, name='excluir-tipo-empresa'),
    path('minha_empresa/cadastrar', views.cadastrar_minha_empresa, name='cadastrar-minha-empresa'),
    path('editar/minha_empresa/<int:id_minha_empresa>', views.editar_minha_empresa, name='editar-minha-empresa'),
    path('empresas', views.listar_empresas, name='empresas'),
    path('empresas/cadastrar', views.cadastrar_empresa, name='cadastrar-empresa'),
    path('editar/empresa/<int:id_empresa>', views.editar_empresa, name='editar-empresa'),
    path('excluir/empresa/<int:id_empresa>', views.excluir_empresa, name='excluir-empresa'),
    path('clientes/', views.listar_clientes, name='clientes'),
    path('buscar/cliente', views.buscar_dados_clientes, name='buscar-cliente'),
    path('clientes/cadastrar', views.cadastrar_cliente, name='cadastrar-cliente'),
    path('editar/cliente/<int:id_cliente>', views.editar_cliente, name='editar-cliente'),
    path('excluir/cliente/<int:id_cliente>', views.excluir_cliente, name='excluir-cliente'),
    path('prepostos/', views.listar_prepostos, name='prepostos'),
    path('prepostos/cadastrar/', views.cadastrar_preposto, name='cadastrar-preposto'),
    path('editar/preposto/<int:id_preposto>', views.editar_preposto, name='editar-preposto'),
    path('remover/preposto/<int:id_preposto>', views.excluir_preposto, name='excluir-preposto'),
    path('rotas-prepostos', views.listar_rotas_prepostos, name='rotas-prepostos'),
    path('rotas-prepostos/retorna_informacoes_preposto', views.retorna_informacoes_preposto, name='retorna-informacoes-preposto'),
    path('rotas-prepostos/cadastrar', views.cadastrar_rotas_prepostos, name='cadastrar-rotas-prepostos'),
    path('rotas-prepostos/retorna_informacoes_rota_prepostos/<int:id_rota>', views.retorna_informacoes_rota_prepostos, name='retorna-informacoes-rota-prepostos'),
    path('editar/rota/<int:id_rota>', views.editar_rotas_prepostos, name='editar-rota'),
    path('remover/rota/<int:id_rota>', views.excluir_rota, name='excluir-rota'),
    path('contatos', views.listar_contatos, name='contatos'),
    path('contatos/cadastrar', views.cadastrar_contato, name='cadastrar-contato'),
    path('editar/contato/<int:id_contato>', views.editar_contato, name='editar-contato'),
    path('remover/contato/<int:id_contato>', views.excluir_contato, name='excluir-contato'),
    path('categorias/', views.listar_categorias, name='categorias'),
    path('categorias/cadastrar', views.cadastrar_categoria, name='cadastrar-categoria'),
    path('editar/categoria/<int:id_categoria>', views.editar_categoria, name='editar-categoria'),
    path('remover/categoria/<int:id_categoria>', views.excluir_categoria, name='excluir-categoria'),
    path('unidades-venda/', views.listar_unidades_venda, name='unidades-venda'),
    path('unidades-venda/cadastrar', views.cadastrar_unidade_venda, name='cadastrar-unidade-venda'),
    path('editar/unidade_venda/<int:id_unidade_venda>', views.editar_unidade_venda, name='editar-unidade-venda'),
    path('remover/unidade_venda/<int:id_unidade_venda>', views.excluir_unidade_venda, name='excluir-unidade-venda'),
    path('tipos-embalagem/', views.listar_tipos_embalagem, name='tipos-embalagem'),
    path('tipos-embalagem/cadastrar', views.cadastrar_tipo_embalagem, name='cadastrar-tipo-embalagem'),
    path('editar/tipo_embalagem/<int:id_tipo_embalagem>', views.editar_tipo_embalagem, name='editar-tipo-embalagem'),
    path('remover/tipo_embalagem/<int:id_tipo_embalagem>', views.excluir_tipo_embalagem, name='excluir-tipo-embalagem'),
    path('produtos', views.listar_produtos, name='produtos'),
    path('produtos/cadastrar', views.cadastrar_produto, name='cadastrar-produto'),
    path('editar/produto/<int:id_produto>', views.editar_produto, name='editar-produto'),
    path('remover/produto/<int:id_produto>', views.excluir_produto, name='excluir-produto'),
    path('formas-pagamento/', views.listar_formas_pagamento, name='formas-pagamento'),
    path('formas-pagamento/cadastrar', views.cadastrar_forma_pagamento, name='cadastrar-forma-pagamento'),
    path('editar/forma_pagamento/<int:id_forma_pagamento>', views.editar_forma_pagamento, name='editar-forma-pagamento'),
    path('remover/forma_pagamento/<int:id_forma_pagamento>', views.excluir_forma_pagamento, name='excluir-forma-pagamento'),
    path('pedidos/', views.listar_pedidos, name='pedidos'),
    path('pedidos/cadastrar', views.cadastrar_pedido, name='cadastrar-pedido'),
    path('pedidos/confirmar_itens_pedido/<int:id_pedido>', views.confirmar_itens_pedido, name='confirmar-itens-pedido'),
    path('editar/pedido/<int:id_pedido>', views.editar_pedido, name='editar-pedido'),
    path('cadastrar/itens_pedido/<int:id_pedido>', views.cadastrar_itens_pedido, name='cadastrar-itens-pedido'),
    path('pedidos/retorna_informacoes_itens_pedido/<int:id_pedido>', views.retorna_informacoes_itens_pedido, name='retorna-informacoes-itens-pedido'),
    path('editar/itens_pedido/<int:id_pedido>', views.editar_itens_pedido, name='editar-itens-pedido'),
    path('remover/pedido/<int:id_pedido>', views.excluir_pedido, name='excluir-pedido'),
    path('gerar-pdf/pedido/<int:id_pedido>', views.gerar_pdf_pedido, name='gerar-pdf-pedido'),
    path('tendencias', views.acompanhamentos, name='acompanhamentos'),
    path('tendencias/cadastrar', views.cadastrar_acompanhamento, name='cadastrar-acompanhamento'),
    path('editar/tendencia/<int:id_acompanhamento>', views.editar_acompanhamento, name='editar-acompanhamento'),
    path('excluir/tendencia/<int:id_acompanhamento>', views.excluir_acompanhamento, name='excluir-acompanhamento'),
    path('prospecoes-clientes', views.prospeccoes_clientes, name="prospeccoes-clientes"),
    path('clientes-sem-pedido', views.clientes_sem_pedido, name="clientes-sem-pedido"),
    path('cancelamentos-pedidos-por-cliente', views.cancelamento_pedidos_por_cliente, name="cancelamentos-pedidos-clientes"),
    path('tarefas', views.listar_tarefas, name='tarefas'),
    path('tarefas/cadastrar', views.cadastrar_tarefa, name='cadastrar-tarefa'),
    path('editar/tarefa/<int:id_tarefa>', views.editar_tarefa, name="editar-tarefa"),
    path('excluir/tarefa<int:id_tarefa>', views.excluir_tarefa, name="excluir-tarefa"),
    path('configuracoes/pedidos', views.configuracoes_pedidos, name="configuracoes-pedidos"),
]

urlpatterns += customizacoes_urls

oli2/representacao/models/configuracoes.py
from django.db import models

class Configuracoes(models.Model):
    id_configuracoes = models.AutoField(primary_key=True)
    codigo = models.CharField(max_length=100)
    descricao = models.TextField()
    valor = models.CharField(max_length=255)

    def __str__(self):
        return self.codigo

oli2/representacao/models/produtos.py
from .empresas import Empresas
from django.db import models


class Categorias(models.Model):
    id_categoria = models.AutoField(primary_key=True)
    nome_categoria = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.nome_categoria


class UnidadesVenda(models.Model):
    id_unidade_venda = models.AutoField(primary_key=True)
    sigla = models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.sigla


class TiposEmbalagem(models.Model):
    id_tipo_embalagem = models.AutoField(primary_key=True)
    tipo = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.tipo


class Produtos(models.Model):
    id_produto = models.AutoField(primary_key=True)
    codigo_produto = models.CharField(max_length=150, null=True, db_index=True)
    descricao = models.CharField(max_length=255, null=True, db_index=True)
    custo_unitario = models.DecimalField(default=0, blank=True, max_digits=10, decimal_places=2)
    comissao = models.DecimalField(default=0, blank=True, max_digits=5, decimal_places=2)
    ipi = models.FloatField(default=0, null=True, blank=True)
    aliquota = models.FloatField(default=0, null=True, blank=True)
    reducao_icms = models.FloatField(default=0, null=True, blank=True)
    st = models.FloatField(default=0, null=True, blank=True)
    pis = models.FloatField(default=0, null=True, blank=True)
    mva_st = models.FloatField(default=0, null=True, blank=True)
    quantidade_embalagem = models.IntegerField(default=0, blank=True)
    validade = models.IntegerField(default=0, blank=True)
    imagem = models.ImageField(null=True, blank=True, upload_to='produtos/')
    ean = models.FloatField(default=0, null=True, blank=True)
    dun = models.FloatField(default=0, null=True, blank=True)
    preco_total = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    id_unidade_venda = models.ForeignKey(UnidadesVenda, on_delete=models.PROTECT)
    id_tipo_embalagem = models.ForeignKey(TiposEmbalagem, on_delete=models.PROTECT)
    id_categoria = models.ForeignKey(Categorias, on_delete=models.PROTECT)
    empresa = models.ManyToManyField(Empresas)

    def __str__(self):
        return self.codigo_produto + ' - ' + self.descricao

oli2/representacao/forms/configuracoes.py
from ..models import *
from django import forms
from django.forms import ModelForm

class ConfiguracoesForm(forms.Form):
    pe01 = forms.BooleanField(required=False)
    pe02 = forms.CharField(max_length=100)
    cg01 = forms.BooleanField(required=False)

oli2/representacao/forms/customizacoes.py
from ..models import *
from django import forms
from django_select2 import forms as s2forms

class CustomizacoesForm(forms.Form):
    chamada = forms.CharField(max_length=100)
    descricao = forms.CharField(max_length=255)
    empresa = forms.ModelChoiceField(queryset=Empresas.objects.none())
    produtos = forms.ModelMultipleChoiceField(queryset=Produtos.objects.none(), widget=s2forms.Select2MultipleWidget())

    def __init__(self, *args, **kwargs):
        super(CustomizacoesForm, self).__init__(*args, **kwargs)
        self.fields['empresa'].queryset = Empresas.objects.all()
        self.fields['produtos'].queryset = Produtos.objects.all()

oli2/api/views/produtos.py
from rest_framework import viewsets
from representacao.models import *
from api.serializers import *


class CategoriasViewSet(viewsets.ModelViewSet):
    queryset = Categorias.objects.all()
    serializer_class = CategoriasSerializer


class UnidadesVendaViewSet(viewsets.ModelViewSet):
    queryset = UnidadesVenda.objects.all()
    serializer_class = UnidadesVendaSerializer


class TiposEmbalagemViewSet(viewsets.ModelViewSet):
    queryset = TiposEmbalagem.objects.all()
    serializer_class = TiposEmpresaSerializer


class ProdutosViewSet(viewsets.ModelViewSet):
    queryset = Produtos.objects.all()
    serializer_class = ProdutosSerializer

oli2/representacao/views/configuracoes.py
import distutils
from ..models import *
from ..forms import *
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from .funcoes import *

@login_required
def configuracoes_pedidos(request, template_name='configuracoes/configuracoes_pedidos.html'):
    pe01 = get_object_or_404(Configuracoes, pk=1)
    pe02 = get_object_or_404(Configuracoes, pk=2)

    if request.method == "POST":
        form = ConfiguracoesForm(request.POST)
        if form.is_valid():
            pe01.valor = form.cleaned_data['pe01']
            pe01.save()
            pe02.valor = form.cleaned_data['pe02']
            pe02.save()

    else:
        form = ConfiguracoesForm()
        form.fields['pe01'].initial = eval(pe01.valor)
        form.fields['pe02'].initial = pe02.valor

    return render(request, template_name, {'form': form, 'pe01': pe01, 'pe02': pe02})

oli2/representacao/views/customizacoes.py
import json
from django.views.decorators.csrf import csrf_exempt
from ..models import *
from ..forms import *
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse


@login_required
def criar_oferta(request, template_name='customizacoes/ofertas_form.html'):
    form = CustomizacoesForm(request.POST or None)

    if form.is_valid():
        chamada = form.cleaned_data['chamada']
        descricao = form.cleaned_data['descricao']
        logo_empresa = form.cleaned_data['empresa'].logo.url
        produtos = form.cleaned_data['produtos']

        request.session['logo_empresa'] = logo_empresa
        request.session['chamada'] = chamada
        request.session['descricao'] = descricao
        request.session['produtos'] = list(produtos.values('id_produto'))

        return redirect('gerar-imagem-oferta')
    produtos = Produtos.objects.all()

    return render(request, template_name, {'form': form, 'produtos': produtos})


@csrf_exempt
def retorna_informacoes_produtos_empresa(request):
    if request.is_ajax() and request.method == "POST":
        data = request.body
        id_empresa = json.loads(data)
        empresa = get_object_or_404(Empresas, pk=id_empresa)
        produtos = Produtos.objects.filter(empresa=empresa).all().values()

        return JsonResponse({'produtos_empresa': list(produtos)})


@csrf_exempt
def gerar_imagem(request, template_name='customizacoes/gerador_imagem.html'):
    logo_empresa = request.session.get('logo_empresa')
    chamada = request.session.get('chamada')
    descricao = request.session.get('descricao')
    produtos_ids = request.session.get('produtos')
    ids = []

    for produto_id in produtos_ids:
        ids.append(produto_id['id_produto'])

    produtos_banco = Produtos.objects.filter(id_produto__in=ids).all()
    minha_empresa = get_object_or_404(MinhaEmpresa, pk=1)
    logo_minha_empresa = minha_empresa.logo.url

    return render(request, template_name, {'logo_empresa': logo_empresa, 'logo_minha_empresa':logo_minha_empresa, 'produtos': produtos_banco, 'descricao': descricao, 'chamada':chamada})

oli2/representacao/views/funcoes.py
from django.contrib import messages, auth

def mensagem_edicao_sucesso(request):
    messages.success(request, 'Atualizado com sucesso')


def mensagem_cadastro_sucesso(request):
    messages.success(request, 'Cadastro realizado com sucesso')

oli2/representacao/templates/produtos/categoria_form.html
{% extends 'partials/dashboard.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container-fluid">
    <h1 class="h3 mb-4 text-gray-800">Cadastro de categorias</h1>
    <div>
        <form action="{{ request.path }}" method="post">
            <div class="form-row mt-2">
                <div class="form-group col-md-5">
                    <label class="font-weight-bold">Nome da categoria</label>
                    {% render_field form.nome_categoria class="form-control" placeholder="Ex: Commodities" %}
                </div>
            </div>
            {% include 'partials/submit.html' %}
        </form>
    </div>
</div>
{% endblock %}

oli2/representacao/templates/produtos/lista_categorias.html
{% extends 'partials/dashboard.html' %}
{% load widget_tweaks %}
{% block content %}
    <div class="container-fluid">
        <h1 class="h3 mb-4 text-gray-800">Categorias cadastradas</h1>
        <div id="formulario-pesquisa" class="d-none">
            <form action="{{ request.path }}">
                <div class="form-row">
                    <div class="form-group col-md-12">
                          <label class="font-weight-bold">Nome</label>
                          {% render_field form.nome_categoria class="form-control" placeholder="Ex: Commodities"%}
                    </div>
                </div>
                <div class="form-row mb-2">
                    <div class="form-group mr-2 mb-0 col-md-5">
                        <input type="submit" class="btn btn-dark mb-2" value="Pesquisar"/>
                    </div>
                </div>
            </form>
        </div>
        {% include 'partials/botao_pesquisa.html' %}
        {% if categorias %}
        <div class="card shadow mb-4">
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    {% for categoria in categorias %}
                        <li class="list-group-item">
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                    <p class="font-weight-bold"> {{ categoria.nome_categoria }}</p>
                                </div>
                            </div>
                            <div class="d-flex">
                                <a href="{% url 'editar-categoria' categoria.id_categoria %}" class="btn btn-success text-white">Editar</a>
                                <a href="{% url 'excluir-categoria' categoria.id_categoria %}" class="btn btn-danger ml-2 text-white">Excluir</a>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div>
            {% if categorias.has_other_pages %}
            <ul class="pagination">
                {% if categorias.has_previous %}
                <li class="page-item">
                    <a href="?page={{ categorias.previous_page_number }}" class="page-link">&laquo;</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link">&laquo;</a>
                </li>
                {% endif %}
                {% for page in categorias.paginator.page_range %}
                {% if categorias.number == page %}
                <li class="page-item active">
                    <a class="page-link">{{ page }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a href="?page={{ page }}" class="page-link">{{ page }}</a>
                </li>
                {% endif %}
                {% endfor %}
                {% if categorias.has_next %}
                <li class="page-item">
                    <a href="?page={{ categorias.next_page_number }}" class="page-link">&raquo;</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link">&raquo;</a>
                </li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
        {% else %}
        {% include 'partials/sem_registros.html' %}
        {% endif %}
    </div>
{% endblock %}
{% block custom-scripts %}
    {% include 'partials/pesquisa_script.html' %}
{% endblock %}

oli2/representacao/templates/produtos/produto_form.html
{% extends 'partials/dashboard.html' %}
{% load widget_tweaks %}
{% block custom-css%}
{{ form.media.css }}
<style>
    input, select {width: 100%}
</style>
{% endblock %}
{% block content %}
<div class="container-fluid">
    <h1 class="h3 mb-4 text-gray-800">Cadastro de produtos</h1>
    <div>
        <form action="{{ request.path }}" method="post" enctype='multipart/form-data'>
            {% include 'partials/submit.html' %}
            <div id="imagem-selecionada">
                {% if form.instance.imagem  %}
                    <img width="200" src="{{ form.instance.imagem.url }}">
                {% endif %}
            </div>
            <div class="form-row mt-4 mb-3">
                <div class="form-group col-md-12">
                    <label class="font-weight-bold">Imagem</label>
                    <div class="imagem">
                        {% render_field form.imagem %}
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div id="campo-multiplo-produto" class="d-none">
                    <label class="font-weight-bold">Múltiplo de venda</label>
                    {% render_field form.multiplo class="form-control" %}
                </div>
                <div class="form-group col-md-12">
                    <label class="font-weight-bold">Categoria</label>
                    {% render_field form.id_categoria class="form-control" %}
                </div>
                <div class="form-group col-md-2">
                    <label class="font-weight-bold">Código</label>
                    {% render_field form.codigo_produto class="form-control" placeholder="Ex: 00001" %}
                </div>
                <div class="form-group col-md-4">
                    <label class="font-weight-bold">Descrição</label>
                    {% render_field form.descricao class="form-control" placeholder="Ex: Batata"%}
                </div>
                <div class="form-group col-md-2">
                    <label class="font-weight-bold">Preço Unitário</label>
                    {% render_field form.custo_unitario class="form-control" %}
                </div>
                <div class="form-group col-md-2">
                    <label class="font-weight-bold">Comissão</label>
                    {% render_field form.comissao class="form-control" %}
                </div>
                <div class="form-group col-md-2">
                    <label class="font-weight-bold">IPI</label>
                    {% render_field form.ipi class="form-control" %}
                </div>
                <div class="form-group col-md-4">
                    <label class="font-weight-bold">Aliquota</label>
                    {% render_field form.aliquota class="form-control" %}
                </div>
                <div class="form-group col-md-2">
                    <label class="font-weight-bold">Redução ICMS</label>
                    {% render_field form.reducao_icms class="form-control" %}
                </div>
                <div class="form-group col-md-1">
                    <label class="font-weight-bold">ST</label>
                    {% render_field form.st class="form-control" %}
                </div>
                <div class="form-group col-md-2">
                    <label class="font-weight-bold">PIS</label>
                    {% render_field form.pis class="form-control" %}
                </div>
                <div class="form-group col-md-3">
                    <label class="font-weight-bold">MVA ST</label>
                    {% render_field form.mva_st class="form-control" %}
                </div>
                <div class="form-group col-md-6">
                    <label class="font-weight-bold">EAN / GETIN 13</label>
                    {% render_field form.ean class="form-control" %}
                </div>
                <div class="form-group col-md-6">
                    <label class="font-weight-bold">DUN / GETIN 14</label>
                    {% render_field form.dun class="form-control" %}
                </div>
                <div class="form-group col-md-2">
                    <label class="font-weight-bold">Unidade de Venda</label>
                    {% render_field form.id_unidade_venda class="form-control" %}
                </div>
                <div class="form-group col-md-3">
                    <label class="font-weight-bold">Tipo de Embalagem</label>
                    {% render_field form.id_tipo_embalagem class="form-control" %}
                </div>
                <div class="form-group col-md-4">
                    <label class="font-weight-bold">Quantidade da Embalagem</label>
                    {% render_field form.quantidade_embalagem class="form-control" %}
                </div>
                <div class="form-group col-md-3">
                    <label class="font-weight-bold">Validade</label>
                    {% render_field form.validade class="form-control" %}
                </div>
                <div class="form-group col-md-12">
                    <label class="font-weight-bold">Preço Total</label>
                    {% render_field form.preco_total class="form-control" %}
                </div>
                <div class="form-group col-md-12">
                    <label class="font-weight-bold">Empresa</label>
                    {% render_field form.empresa class="form-control" %}
                </div>
            </div>
            {% render_field form.errors %}
        </form>
    </div>
</div>
{% endblock %}
{% block custom-scripts %}
{{ form.media.js }}
<script>
    let calculaPreco = () => {
        let quantidadeEmbalagem = $("#id_quantidade_embalagem").val();

        if(quantidadeEmbalagem > 0){
            let preco = $("#id_custo_unitario").val();
            $("#id_preco_total").val(preco * quantidadeEmbalagem);
        }
        else {
            let preco = $("#id_custo_unitario").val();
            $("#id_preco_total").val(preco);
        }
    }

    $(document).ready(function(){
        $("input[type=file]").on("change", function() {
            let fileName = $(this).val().split("\\").pop();

            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);

            mostraImagem();
        });

        $("#id_custo_unitario").change(function(){
            calculaPreco();
        });

        $("#id_quantidade_embalagem").change(function(){
            calculaPreco();
        });
    });
</script>
{% endblock %}

oli2/representacao/templates/produtos/tipo_embalagem_form.html
{% extends 'partials/dashboard.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container-fluid">
    <h1 class="h3 mb-4 text-gray-800">Cadastro de tipos de embalagem</h1>
    <div>
        <form action="{{ request.path }}" method="post">
            <div class="form-row mt-2">
                <div class="form-group col-md-5">
                    <label class="font-weight-bold">Tipo</label>
                    {% render_field form.tipo class="form-control" placeholder="Ex: Caixa" %}
                </div>
            </div>
            {% include 'partials/submit.html' %}
        </form>
    </div>
</div>
{% endblock %}

oli2/representacao/templates/produtos/unidade_venda_form.html
{% extends 'partials/dashboard.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container-fluid">
    <h1 class="h3 mb-4 text-gray-800">Cadastro de unidades de venda</h1>
    <div>
        <form action="{{ request.path }}" method="post">
            <div class="form-row mt-2">
                <div class="form-group col-md-5">
                    <label class="font-weight-bold">Sigla</label>
                    {% render_field form.sigla class="form-control" placeholder="Ex: Kg" %}
                </div>
            </div>
            {% include 'partials/submit.html' %}
        </form>
    </div>
</div>
{% endblock %}