oli2/api/urls.py
from api.views.configuracoes import *
from api.views.empresas import *
from api.views.pessoas import *
from api.views.pedidos import *
from api.views.usuarios import *
from api.views.relatorios import *
from api.views.produtos import *
from rest_framework import routers

router = routers.DefaultRouter()
router.register('configuracoes', ConfiguracoesViewSet, 'Configuracoes')
router.register('empresas', EmpresasViewSet, 'Empresas')
router.register('minha_empresa', MinhaEmpresaViewSet, 'MinhaEmpresa')
router.register('tipos_empresa', TiposEmpresaViewSet, 'TiposEmpresa')
router.register('clientes', ClientesViewSet, 'Clientes')
router.register('prepostos', PrepostosViewSet, 'Prepostos')
router.register('rotas', RotasViewSet, 'Rotas')
router.register('rotas_prepostos', RotasPrepostosViewSet, 'RotasPrepostos')
router.register('preposto_clientes', PrepostoClientesViewSet, 'PrepostoClientes')
router.register('contatos', ContatosViewSet, 'Contatos')
router.register('formas_pagamento', FormasPagamentoViewSet, 'FormasPagamento')
router.register('pedidos', PedidosViewSet, 'Pedidos')
router.register('itens_pedido', ItensPedidoViewSet, 'ItensPedido')
router.register('categorias', CategoriasViewSet, 'Categorias')
router.register('unidades_venda', UnidadesVendaViewSet, 'UnidadesVenda')
router.register('tipos_embalagem', TiposEmbalagemViewSet, 'TiposEmbalagem')
router.register('produtos', ProdutosViewSet, 'Produtos')
router.register('acompanhamentos', AcompanhamentosViewSet, 'Acompanhamentos')
router.register('acompanhamento_empresa', AcompanhamentoEmpresaViewSet, 'AcompanhamentoEmpresa')
router.register('acompanhamento_preposto_empresa', AcompanhamentoPrepostoEmpresaViewSet, 'AcompanhamentoPrepostoEmpresa')
router.register('usuarios', UsuariosViewSet, 'Usuarios')
router.register('tarefas', TarefasViewSet, 'Tarefas')

urlpatterns = router.urls

oli2/representacao/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .customizacoes_urls import urlpatterns as customizacoes_urls
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login', auth_views.LoginView.as_view(template_name='usuarios/login.html'), name='login'),
    path('autenticar', views.autenticar, name='autenticar'),
    path('logout', auth_views.LogoutView.as_view(template_name='usuarios/logout.html'), name='logout'),
    path('usuarios/', views.listar_usuarios, name='usuarios'),
    path('usuarios/cadastrar', views.cadastrar_usuario, name='cadastrar-usuario'),
    path('editar/usuario/<int:id_usuario>', views.editar_usuario, name='editar-usuario'),
    path('remover/usuario/<int:id_usuario>', views.excluir_usuario, name='excluir-usuario'),
    path('tipos-empresa/', views.listar_tipos_empresa, name='tipos-empresa'),
    path('tipos-empresa/cadastrar', views.cadastrar_tipo_empresa, name='cadastrar-tipo-empresa'),
    path('editar/tipo_empresa/<int:id_tipo_empresa>', views.editar_tipo_empresa, name='editar-tipo-empresa'),
    path('remover/tipo_empresa/<int:id_tipo_empresa>', views.excluir_tipo_empresa, name='excluir-tipo-empresa'),
    path('minha_empresa/cadastrar', views.cadastrar_minha_empresa, name='cadastrar-minha-empresa'),
    path('editar/minha_empresa/<int:id_minha_empresa>', views.editar_minha_empresa, name='editar-minha-empresa'),
    path('empresas', views.listar_empresas, name='empresas'),
    path('empresas/cadastrar', views.cadastrar_empresa, name='cadastrar-empresa'),
    path('editar/empresa/<int:id_empresa>', views.editar_empresa, name='editar-empresa'),
    path('excluir/empresa/<int:id_empresa>', views.excluir_empresa, name='excluir-empresa'),
    path('clientes/', views.listar_clientes, name='clientes'),
    path('buscar/cliente', views.buscar_dados_clientes, name='buscar-cliente'),
    path('clientes/cadastrar', views.cadastrar_cliente, name='cadastrar-cliente'),
    path('editar/cliente/<int:id_cliente>', views.editar_cliente, name='editar-cliente'),
    path('excluir/cliente/<int:id_cliente>', views.excluir_cliente, name='excluir-cliente'),
    path('prepostos/', views.listar_prepostos, name='prepostos'),
    path('prepostos/cadastrar/', views.cadastrar_preposto, name='cadastrar-preposto'),
    path('editar/preposto/<int:id_preposto>', views.editar_preposto, name='editar-preposto'),
    path('remover/preposto/<int:id_preposto>', views.excluir_preposto, name='excluir-preposto'),
    path('rotas-prepostos', views.listar_rotas_prepostos, name='rotas-prepostos'),
    path('rotas-prepostos/retorna_informacoes_preposto', views.retorna_informacoes_preposto, name='retorna-informacoes-preposto'),
    path('rotas-prepostos/cadastrar', views.cadastrar_rotas_prepostos, name='cadastrar-rotas-prepostos'),
    path('rotas-prepostos/retorna_informacoes_rota_prepostos/<int:id_rota>', views.retorna_informacoes_rota_prepostos, name='retorna-informacoes-rota-prepostos'),
    path('editar/rota/<int:id_rota>', views.editar_rotas_prepostos, name='editar-rota'),
    path('remover/rota/<int:id_rota>', views.excluir_rota, name='excluir-rota'),
    path('contatos', views.listar_contatos, name='contatos'),
    path('contatos/cadastrar', views.cadastrar_contato, name='cadastrar-contato'),
    path('editar/contato/<int:id_contato>', views.editar_contato, name='editar-contato'),
    path('remover/contato/<int:id_contato>', views.excluir_contato, name='excluir-contato'),
    path('categorias/', views.listar_categorias, name='categorias'),
    path('categorias/cadastrar', views.cadastrar_categoria, name='cadastrar-categoria'),
    path('editar/categoria/<int:id_categoria>', views.editar_categoria, name='editar-categoria'),
    path('remover/categoria/<int:id_categoria>', views.excluir_categoria, name='excluir-categoria'),
    path('unidades-venda/', views.listar_unidades_venda, name='unidades-venda'),
    path('unidades-venda/cadastrar', views.cadastrar_unidade_venda, name='cadastrar-unidade-venda'),
    path('editar/unidade_venda/<int:id_unidade_venda>', views.editar_unidade_venda, name='editar-unidade-venda'),
    path('remover/unidade_venda/<int:id_unidade_venda>', views.excluir_unidade_venda, name='excluir-unidade-venda'),
    path('tipos-embalagem/', views.listar_tipos_embalagem, name='tipos-embalagem'),
    path('tipos-embalagem/cadastrar', views.cadastrar_tipo_embalagem, name='cadastrar-tipo-embalagem'),
    path('editar/tipo_embalagem/<int:id_tipo_embalagem>', views.editar_tipo_embalagem, name='editar-tipo-embalagem'),
    path('remover/tipo_embalagem/<int:id_tipo_embalagem>', views.excluir_tipo_embalagem, name='excluir-tipo-embalagem'),
    path('produtos', views.listar_produtos, name='produtos'),
    path('produtos/cadastrar', views.cadastrar_produto, name='cadastrar-produto'),
    path('editar/produto/<int:id_produto>', views.editar_produto, name='editar-produto'),
    path('remover/produto/<int:id_produto>', views.excluir_produto, name='excluir-produto'),
    path('formas-pagamento/', views.listar_formas_pagamento, name='formas-pagamento'),
    path('formas-pagamento/cadastrar', views.cadastrar_forma_pagamento, name='cadastrar-forma-pagamento'),
    path('editar/forma_pagamento/<int:id_forma_pagamento>', views.editar_forma_pagamento, name='editar-forma-pagamento'),
    path('remover/forma_pagamento/<int:id_forma_pagamento>', views.excluir_forma_pagamento, name='excluir-forma-pagamento'),
    path('pedidos/', views.listar_pedidos, name='pedidos'),
    path('pedidos/cadastrar', views.cadastrar_pedido, name='cadastrar-pedido'),
    path('pedidos/confirmar_itens_pedido/<int:id_pedido>', views.confirmar_itens_pedido, name='confirmar-itens-pedido'),
    path('editar/pedido/<int:id_pedido>', views.editar_pedido, name='editar-pedido'),
    path('cadastrar/itens_pedido/<int:id_pedido>', views.cadastrar_itens_pedido, name='cadastrar-itens-pedido'),
    path('pedidos/retorna_informacoes_itens_pedido/<int:id_pedido>', views.retorna_informacoes_itens_pedido, name='retorna-informacoes-itens-pedido'),
    path('editar/itens_pedido/<int:id_pedido>', views.editar_itens_pedido, name='editar-itens-pedido'),
    path('remover/pedido/<int:id_pedido>', views.excluir_pedido, name='excluir-pedido'),
    path('gerar-pdf/pedido/<int:id_pedido>', views.gerar_pdf_pedido, name='gerar-pdf-pedido'),
    path('tendencias', views.acompanhamentos, name='acompanhamentos'),
    path('tendencias/cadastrar', views.cadastrar_acompanhamento, name='cadastrar-acompanhamento'),
    path('editar/tendencia/<int:id_acompanhamento>', views.editar_acompanhamento, name='editar-acompanhamento'),
    path('excluir/tendencia/<int:id_acompanhamento>', views.excluir_acompanhamento, name='excluir-acompanhamento'),
    path('prospecoes-clientes', views.prospeccoes_clientes, name="prospeccoes-clientes"),
    path('clientes-sem-pedido', views.clientes_sem_pedido, name="clientes-sem-pedido"),
    path('cancelamentos-pedidos-por-cliente', views.cancelamento_pedidos_por_cliente, name="cancelamentos-pedidos-clientes"),
    path('tarefas', views.listar_tarefas, name='tarefas'),
    path('tarefas/cadastrar', views.cadastrar_tarefa, name='cadastrar-tarefa'),
    path('editar/tarefa/<int:id_tarefa>', views.editar_tarefa, name="editar-tarefa"),
    path('excluir/tarefa<int:id_tarefa>', views.excluir_tarefa, name="excluir-tarefa"),
    path('configuracoes/pedidos', views.configuracoes_pedidos, name="configuracoes-pedidos"),
]

urlpatterns += customizacoes_urls

oli2/representacao/forms/configuracoes.py
from ..models import *
from django import forms
from django.forms import ModelForm

class ConfiguracoesForm(forms.Form):
    pe01 = forms.BooleanField(required=False)
    pe02 = forms.CharField(max_length=100)
    cg01 = forms.BooleanField(required=False)

oli2/representacao/forms/customizacoes.py
from ..models import *
from django import forms
from django_select2 import forms as s2forms

class CustomizacoesForm(forms.Form):
    chamada = forms.CharField(max_length=100)
    descricao = forms.CharField(max_length=255)
    empresa = forms.ModelChoiceField(queryset=Empresas.objects.none())
    produtos = forms.ModelMultipleChoiceField(queryset=Produtos.objects.none(), widget=s2forms.Select2MultipleWidget())

    def __init__(self, *args, **kwargs):
        super(CustomizacoesForm, self).__init__(*args, **kwargs)
        self.fields['empresa'].queryset = Empresas.objects.all()
        self.fields['produtos'].queryset = Produtos.objects.all()

oli2/representacao/forms/empresas.py
from ..models import *
from django import forms
from django.forms import ModelForm


class TipoEmpresaForm(ModelForm):
    class Meta:
        model = TiposEmpresa
        labels: {'Tipo'}
        fields = '__all__'


class PesquisaTipoEmpresaForm(forms.Form):
    tipo = forms.CharField(required=False, max_length=255)


class MinhaEmpresaForm(ModelForm):
    class Meta:
        model = MinhaEmpresa
        fields = '__all__'


class EmpresaForm(ModelForm):
    class Meta:
        model = Empresas
        fields = '__all__'


class PesquisaEmpresaForm(forms.Form):
    razao_social = forms.CharField(max_length=255, required=False)
    nome_fantasia = forms.CharField(max_length=255, required=False)
    cnpj = forms.CharField(max_length=50, required=False)
    inscricao_estadual = forms.CharField(max_length=25, required=False)
    tipo_empresa = forms.ModelChoiceField(required=False, queryset=TiposEmpresa.objects.none())

    def __init__(self, *args, **kwargs):
        super(PesquisaEmpresaForm, self).__init__(*args, **kwargs)
        self.fields['tipo_empresa'].queryset = TiposEmpresa.objects.all()


class ClienteForm(ModelForm):
    class Meta:
        model = Clientes
        fields = '__all__'


class PesquisaClienteForm(forms.Form):
    razao_social = forms.CharField(max_length=255, required=False)
    nome_fantasia = forms.CharField(max_length=255, required=False)
    cnpj = forms.CharField(max_length=50, required=False)
    inscricao_estadual = forms.CharField(max_length=25, required=False)

oli2/representacao/forms/relatorios.py
from ..models import *
from django import forms
from django.forms import ModelForm
from tempus_dominus.widgets import DatePicker


class AcompanhamentoForm(ModelForm):
    class Meta:
        model = Acompanhamentos
        fields = '__all__'
        widgets = {
            'data_inicial': DatePicker(),
            'data_final': DatePicker(),
        }


class ProspeccoesClientesForm(forms.Form):
    QUANTIDADE = (
        ('TODOS', 'TODOS OS USUÁRIOS'),
        ('1', 'USUÁRIO QUE MAIS PROSPECTOU'),
        ('5', '5 USUÁRIOS QUE MAIS PROSPECTARAM'),
        ('15', '15 USUÁRIOS QUE MAIS PROSPECTARAM'),
        ('30', '30 USUÁRIOS QUE MAIS PROSPECTARAM'),
        ('50', '50 USUÁRIOS QUE MAIS PROSPECTARAM')
    )

    TIPO_PESQUISA = (
        ('Filtrar Todos', 'Filtrar todos'),
        ('Filtrar especifico', 'Filtrar específico')
    )

    usuario = forms.ModelChoiceField(required=False, queryset=Usuarios.objects.none())
    quantidade_maxima = forms.ChoiceField(required=False, choices=QUANTIDADE)
    tipo_pesquisa = forms.ChoiceField(required=False, choices=TIPO_PESQUISA, widget=forms.RadioSelect)

    def __init__(self, *args, **kwargs):
        super(ProspeccoesClientesForm, self).__init__(*args, **kwargs)
        self.fields['usuario'].queryset = Usuarios.objects.all()


class ClientesSemPedidoForm(forms.Form):
    data_inicial = forms.DateField(required=True, widget=DatePicker())
    data_final = forms.DateField(required=True, widget=DatePicker())


class CancelamentoPedidosPorCliente(forms.Form):
    data_inicial = forms.DateField(required=False, widget=DatePicker())
    data_final = forms.DateField(required=False, widget=DatePicker())

oli2/api/views/relatorios.py
from rest_framework import viewsets
from representacao.models import *
from api.serializers import *


class AcompanhamentosViewSet(viewsets.ModelViewSet):
    queryset = Acompanhamentos.objects.all()
    serializer_class = AcompanhamentosSerializer


class AcompanhamentoEmpresaViewSet(viewsets.ModelViewSet):
    queryset = AcompanhamentoEmpresa.objects.all()
    serializer_class = AcompanhamentosSerializer


class AcompanhamentoPrepostoEmpresaViewSet(viewsets.ModelViewSet):
    queryset = AcompanhamentoPrepostoEmpresa.objects.all()
    serializer_class = AcompanhamentoPrepostoEmpresaSerializer

oli2/representacao/views/configuracoes.py
import distutils
from ..models import *
from ..forms import *
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from .funcoes import *

@login_required
def configuracoes_pedidos(request, template_name='configuracoes/configuracoes_pedidos.html'):
    pe01 = get_object_or_404(Configuracoes, pk=1)
    pe02 = get_object_or_404(Configuracoes, pk=2)

    if request.method == "POST":
        form = ConfiguracoesForm(request.POST)
        if form.is_valid():
            pe01.valor = form.cleaned_data['pe01']
            pe01.save()
            pe02.valor = form.cleaned_data['pe02']
            pe02.save()

    else:
        form = ConfiguracoesForm()
        form.fields['pe01'].initial = eval(pe01.valor)
        form.fields['pe02'].initial = pe02.valor

    return render(request, template_name, {'form': form, 'pe01': pe01, 'pe02': pe02})

oli2/representacao/views/customizacoes.py
import json
from django.views.decorators.csrf import csrf_exempt
from ..models import *
from ..forms import *
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse


@login_required
def criar_oferta(request, template_name='customizacoes/ofertas_form.html'):
    form = CustomizacoesForm(request.POST or None)

    if form.is_valid():
        chamada = form.cleaned_data['chamada']
        descricao = form.cleaned_data['descricao']
        logo_empresa = form.cleaned_data['empresa'].logo.url
        produtos = form.cleaned_data['produtos']

        request.session['logo_empresa'] = logo_empresa
        request.session['chamada'] = chamada
        request.session['descricao'] = descricao
        request.session['produtos'] = list(produtos.values('id_produto'))

        return redirect('gerar-imagem-oferta')
    produtos = Produtos.objects.all()

    return render(request, template_name, {'form': form, 'produtos': produtos})


@csrf_exempt
def retorna_informacoes_produtos_empresa(request):
    if request.is_ajax() and request.method == "POST":
        data = request.body
        id_empresa = json.loads(data)
        empresa = get_object_or_404(Empresas, pk=id_empresa)
        produtos = Produtos.objects.filter(empresa=empresa).all().values()

        return JsonResponse({'produtos_empresa': list(produtos)})


@csrf_exempt
def gerar_imagem(request, template_name='customizacoes/gerador_imagem.html'):
    logo_empresa = request.session.get('logo_empresa')
    chamada = request.session.get('chamada')
    descricao = request.session.get('descricao')
    produtos_ids = request.session.get('produtos')
    ids = []

    for produto_id in produtos_ids:
        ids.append(produto_id['id_produto'])

    produtos_banco = Produtos.objects.filter(id_produto__in=ids).all()
    minha_empresa = get_object_or_404(MinhaEmpresa, pk=1)
    logo_minha_empresa = minha_empresa.logo.url

    return render(request, template_name, {'logo_empresa': logo_empresa, 'logo_minha_empresa':logo_minha_empresa, 'produtos': produtos_banco, 'descricao': descricao, 'chamada':chamada})

oli2/representacao/views/funcoes.py
from django.contrib import messages, auth

def mensagem_edicao_sucesso(request):
    messages.success(request, 'Atualizado com sucesso')


def mensagem_cadastro_sucesso(request):
    messages.success(request, 'Cadastro realizado com sucesso')

oli2/representacao/templates/relatorios/acompanhamento_form.html
{% extends 'partials/dashboard.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container-fluid">
    <h1 class="h3 mb-4 text-gray-800">Nova tendência</h1>
    <div>
        <form action="{{ request.path }}" method="post">
            {% include 'partials/submit.html' %}
            <div class="form-row mt-2">
                <div class="form-group col-md-6">
                     <label class="font-weight-bold">Meta do mês (R$)</label>
                     {% render_field form.meta_geral class="form-control" %}
                </div>
                <div class="form-group col-md-6">
                     <label class="font-weight-bold">Dias úteis no mes</label>
                     {% render_field form.dias_uteis class="form-control" %}
                </div>
                <div class="form-group col-md-6">
                    <label class="font-weight-bold">Data inicial</label>
                    {% render_field form.data_inicial class="form-control" %}
                </div>
                 <div class="form-group col-md-6">
                    <label class="font-weight-bold">Data final</label>
                    {% render_field form.data_final class="form-control" %}
                </div>
                <div class="form-group col-md-12">
                    <label class="font-weight-bold">Dias trabalhados</label>
                    {% render_field form.dias_trabalhados class="form-control" %}
                </div>
            </div>
        </form>
        <div class="card shadow mb-4">
            {% if tendencia %}
            <div class="text-center">
                <img src="data:image/png;base64,{{ tendencia|safe }}">
            </div>
            {% endif %}
            {% if porcentagem%}
            <div class="text-center">
                <img src="data:image/png;base64,{{ porcentagem|safe }}">
            </div>
            {% endif %}
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <p>Total faturado até o momento: <span class="font-weight-bold">R$ {{ total_faturado_ate }}</span></p>
                        <p>Percentual da meta até o momento: <span class="font-weight-bold">{{ percentual_da_meta_ate }} % </span></p>
                        <p>Tendência de faturamento final: <span class="font-weight-bold">R$ {{ tendencia_de_faturamento }} </span></p>
                        <p>Faturamento diário necessário:
                            {% if total_faturado_ate >= meta_geral %}
                                <span class="font-weight-bold">Meta atingida</span>
                            {% else %}
                                <span class="font-weight-bold">R$ {{ faturamento_diario_necessario }}</span>
                            {% endif %}
                        </p>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

oli2/representacao/templates/relatorios/cancelamento_pedidos_por_cliente_form.html
{% extends 'partials/dashboard.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container-fluid">
    <h1 class="h3 mb-4 text-gray-800">Cancelamentos de pedidos por cliente</h1>
    <div>
        <form action="{{ request.path }}">
            <div class="form-row">
                <div class="form-group col-md-6">
                    {% render_field form.data_inicial class="form-control" placeholder="Ex: dd/mm/aaaa" %}
                </div>
                <div class="form-group col-md-6">
                    {% render_field form.data_final class="form-control" placeholder="Ex: dd/mm/aaaa" %}
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="form-group mr-2 mb-0 col-md-5">
                    <input type="submit" class="btn btn-dark mb-2" value="Pesquisar"/>
                </div>
            </div>
        </form>
        {% if clientes_pedidos_somas %}
            {% for cliente in clientes_pedidos_somas %}
                <div class="card shadow mb-4">
                    <div class="card-body">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">
                                <div class="row align-items-center">
                                    <div class="col-md-6">
                                        <p class="font-weight-bold mb-0">{{ cliente.nome_fantasia }}</p>
                                        <p class="mb-0">Pedidos realizados: {{cliente.pedidos_feitos}}</p>
                                        <p class="mb-0">Pedidos efetivados: {{ cliente.pedidos_nao_cancelados }}</p>
                                        <p class="mb-0">Pedidos cancelados: {{ cliente.pedidos_cancelados }}</p>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            {% endfor %}
        {% else %}
        {% include 'partials/sem_registros.html' %}
        {% endif %}
    </div>
</div>
{% endblock %}

oli2/representacao/templates/relatorios/clientes_sem_pedido_form.html
{% extends 'partials/dashboard.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container-fluid">
    <h1 class="h3 mb-4 text-gray-800">Clientes sem pedido</h1>
    <div>
        <form action="{{ request.path }}">
            <div class="form-row">
                <div class="form-group col-md-6">
                    {% render_field form.data_inicial class="form-control" placeholder="Ex: dd/mm/aaaa" %}
                </div>
                <div class="form-group col-md-6">
                    {% render_field form.data_final class="form-control" placeholder="Ex: dd/mm/aaaa" %}
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="form-group mr-2 mb-0 col-md-5">
                    <input type="submit" class="btn btn-dark mb-2" value="Pesquisar"/>
                </div>
            </div>
        </form>
        {% if clientes_sem_pedidos %}
            {% for cliente in clientes_sem_pedidos %}
                <div class="card shadow mb-4">
                    <div class="card-body">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">
                                <div class="row align-items-center">
                                    <div class="col-md-6">
                                        <p class="font-weight-bold">{{ cliente.nome_fantasia }}</p>
                                        <p class="mb-0">Último pedido: {{ cliente.data_ultimo_pedido.date }}</p>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            {% endfor %}
        {% else %}
        {% include 'partials/sem_registros.html' %}
        {% endif %}
    </div>
</div>
{% endblock %}

oli2/representacao/templates/relatorios/prospeccao_clientes_form.html
{% extends 'partials/dashboard.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container-fluid">
    <h1 class="h3 mb-4 text-gray-800">Prospecções por usuário</h1>
    <div>
         <form action="{{ request.path }}">
            <div class="form-row">
                <div class="form-group col-md-6">
                    {% render_field form.tipo_pesquisa%}
                </div>
                <div id="campo-quantidade-maxima" class="d-none">
                    <label class="font-weight-bold">Quantidade máxima de resultados</label>
                    {% render_field form.quantidade_maxima class="form-control"%}
                </div>
                <div id="campo-usuario" class="d-none">
                    <label class="font-weight-bold">Usuário</label>
                    {% render_field form.usuario class="form-control"%}
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="form-group mr-2 mb-0 col-md-5">
                    <input type="submit" class="btn btn-dark mb-2" value="Pesquisar"/>
                </div>
            </div>
         </form>
         {% if prospecoes %}
         {% else %}
         {% include 'partials/sem_registros.html' %}
         {% endif %}
    </div>
</div>
{% endblock %}
{% block custom-scripts %}
<script>
    let mostraEscondeCampos = () => {
        if($("#id_tipo_pesquisa_0").is(":checked")){
            $("#campo-quantidade-maxima")
                .removeClass("d-none")
                .addClass("form-group col-md-12");

            $("#campo-usuario")
                .removeClass("form-group col-md-12")
                .addClass("d-none");
        }
        else{
            $("#campo-quantidade-maxima")
                .removeClass("form-group col-md-12")
                .addClass("d-none");

            $("#campo-usuario")
                .removeClass("d-none")
                .addClass("form-group col-md-12");
        }
    }

    let init = () => {
        $("#id_tipo_pesquisa_0").prop("checked", true);

        mostraEscondeCampos();
    }

    $(document).ready(function(){
        init();

        $("#id_tipo_pesquisa").change(function(){
            mostraEscondeCampos();
        });
    });
</script>
{% endblock %}