oli2/api/urls.py
from api.views.configuracoes import *
from api.views.empresas import *
from api.views.pessoas import *
from api.views.pedidos import *
from api.views.usuarios import *
from api.views.relatorios import *
from api.views.produtos import *
from rest_framework import routers

router = routers.DefaultRouter()
router.register('configuracoes', ConfiguracoesViewSet, 'Configuracoes')
router.register('empresas', EmpresasViewSet, 'Empresas')
router.register('minha_empresa', MinhaEmpresaViewSet, 'MinhaEmpresa')
router.register('tipos_empresa', TiposEmpresaViewSet, 'TiposEmpresa')
router.register('clientes', ClientesViewSet, 'Clientes')
router.register('prepostos', PrepostosViewSet, 'Prepostos')
router.register('rotas', RotasViewSet, 'Rotas')
router.register('rotas_prepostos', RotasPrepostosViewSet, 'RotasPrepostos')
router.register('preposto_clientes', PrepostoClientesViewSet, 'PrepostoClientes')
router.register('contatos', ContatosViewSet, 'Contatos')
router.register('formas_pagamento', FormasPagamentoViewSet, 'FormasPagamento')
router.register('pedidos', PedidosViewSet, 'Pedidos')
router.register('itens_pedido', ItensPedidoViewSet, 'ItensPedido')
router.register('categorias', CategoriasViewSet, 'Categorias')
router.register('unidades_venda', UnidadesVendaViewSet, 'UnidadesVenda')
router.register('tipos_embalagem', TiposEmbalagemViewSet, 'TiposEmbalagem')
router.register('produtos', ProdutosViewSet, 'Produtos')
router.register('acompanhamentos', AcompanhamentosViewSet, 'Acompanhamentos')
router.register('acompanhamento_empresa', AcompanhamentoEmpresaViewSet, 'AcompanhamentoEmpresa')
router.register('acompanhamento_preposto_empresa', AcompanhamentoPrepostoEmpresaViewSet, 'AcompanhamentoPrepostoEmpresa')
router.register('usuarios', UsuariosViewSet, 'Usuarios')
router.register('tarefas', TarefasViewSet, 'Tarefas')

urlpatterns = router.urls

oli2/representacao/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .customizacoes_urls import urlpatterns as customizacoes_urls
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login', auth_views.LoginView.as_view(template_name='usuarios/login.html'), name='login'),
    path('autenticar', views.autenticar, name='autenticar'),
    path('logout', auth_views.LogoutView.as_view(template_name='usuarios/logout.html'), name='logout'),
    path('usuarios/', views.listar_usuarios, name='usuarios'),
    path('usuarios/cadastrar', views.cadastrar_usuario, name='cadastrar-usuario'),
    path('editar/usuario/<int:id_usuario>', views.editar_usuario, name='editar-usuario'),
    path('remover/usuario/<int:id_usuario>', views.excluir_usuario, name='excluir-usuario'),
    path('tipos-empresa/', views.listar_tipos_empresa, name='tipos-empresa'),
    path('tipos-empresa/cadastrar', views.cadastrar_tipo_empresa, name='cadastrar-tipo-empresa'),
    path('editar/tipo_empresa/<int:id_tipo_empresa>', views.editar_tipo_empresa, name='editar-tipo-empresa'),
    path('remover/tipo_empresa/<int:id_tipo_empresa>', views.excluir_tipo_empresa, name='excluir-tipo-empresa'),
    path('minha_empresa/cadastrar', views.cadastrar_minha_empresa, name='cadastrar-minha-empresa'),
    path('editar/minha_empresa/<int:id_minha_empresa>', views.editar_minha_empresa, name='editar-minha-empresa'),
    path('empresas', views.listar_empresas, name='empresas'),
    path('empresas/cadastrar', views.cadastrar_empresa, name='cadastrar-empresa'),
    path('editar/empresa/<int:id_empresa>', views.editar_empresa, name='editar-empresa'),
    path('excluir/empresa/<int:id_empresa>', views.excluir_empresa, name='excluir-empresa'),
    path('clientes/', views.listar_clientes, name='clientes'),
    path('buscar/cliente', views.buscar_dados_clientes, name='buscar-cliente'),
    path('clientes/cadastrar', views.cadastrar_cliente, name='cadastrar-cliente'),
    path('editar/cliente/<int:id_cliente>', views.editar_cliente, name='editar-cliente'),
    path('excluir/cliente/<int:id_cliente>', views.excluir_cliente, name='excluir-cliente'),
    path('prepostos/', views.listar_prepostos, name='prepostos'),
    path('prepostos/cadastrar/', views.cadastrar_preposto, name='cadastrar-preposto'),
    path('editar/preposto/<int:id_preposto>', views.editar_preposto, name='editar-preposto'),
    path('remover/preposto/<int:id_preposto>', views.excluir_preposto, name='excluir-preposto'),
    path('rotas-prepostos', views.listar_rotas_prepostos, name='rotas-prepostos'),
    path('rotas-prepostos/retorna_informacoes_preposto', views.retorna_informacoes_preposto, name='retorna-informacoes-preposto'),
    path('rotas-prepostos/cadastrar', views.cadastrar_rotas_prepostos, name='cadastrar-rotas-prepostos'),
    path('rotas-prepostos/retorna_informacoes_rota_prepostos/<int:id_rota>', views.retorna_informacoes_rota_prepostos, name='retorna-informacoes-rota-prepostos'),
    path('editar/rota/<int:id_rota>', views.editar_rotas_prepostos, name='editar-rota'),
    path('remover/rota/<int:id_rota>', views.excluir_rota, name='excluir-rota'),
    path('contatos', views.listar_contatos, name='contatos'),
    path('contatos/cadastrar', views.cadastrar_contato, name='cadastrar-contato'),
    path('editar/contato/<int:id_contato>', views.editar_contato, name='editar-contato'),
    path('remover/contato/<int:id_contato>', views.excluir_contato, name='excluir-contato'),
    path('categorias/', views.listar_categorias, name='categorias'),
    path('categorias/cadastrar', views.cadastrar_categoria, name='cadastrar-categoria'),
    path('editar/categoria/<int:id_categoria>', views.editar_categoria, name='editar-categoria'),
    path('remover/categoria/<int:id_categoria>', views.excluir_categoria, name='excluir-categoria'),
    path('unidades-venda/', views.listar_unidades_venda, name='unidades-venda'),
    path('unidades-venda/cadastrar', views.cadastrar_unidade_venda, name='cadastrar-unidade-venda'),
    path('editar/unidade_venda/<int:id_unidade_venda>', views.editar_unidade_venda, name='editar-unidade-venda'),
    path('remover/unidade_venda/<int:id_unidade_venda>', views.excluir_unidade_venda, name='excluir-unidade-venda'),
    path('tipos-embalagem/', views.listar_tipos_embalagem, name='tipos-embalagem'),
    path('tipos-embalagem/cadastrar', views.cadastrar_tipo_embalagem, name='cadastrar-tipo-embalagem'),
    path('editar/tipo_embalagem/<int:id_tipo_embalagem>', views.editar_tipo_embalagem, name='editar-tipo-embalagem'),
    path('remover/tipo_embalagem/<int:id_tipo_embalagem>', views.excluir_tipo_embalagem, name='excluir-tipo-embalagem'),
    path('produtos', views.listar_produtos, name='produtos'),
    path('produtos/cadastrar', views.cadastrar_produto, name='cadastrar-produto'),
    path('editar/produto/<int:id_produto>', views.editar_produto, name='editar-produto'),
    path('remover/produto/<int:id_produto>', views.excluir_produto, name='excluir-produto'),
    path('formas-pagamento/', views.listar_formas_pagamento, name='formas-pagamento'),
    path('formas-pagamento/cadastrar', views.cadastrar_forma_pagamento, name='cadastrar-forma-pagamento'),
    path('editar/forma_pagamento/<int:id_forma_pagamento>', views.editar_forma_pagamento, name='editar-forma-pagamento'),
    path('remover/forma_pagamento/<int:id_forma_pagamento>', views.excluir_forma_pagamento, name='excluir-forma-pagamento'),
    path('pedidos/', views.listar_pedidos, name='pedidos'),
    path('pedidos/cadastrar', views.cadastrar_pedido, name='cadastrar-pedido'),
    path('pedidos/confirmar_itens_pedido/<int:id_pedido>', views.confirmar_itens_pedido, name='confirmar-itens-pedido'),
    path('editar/pedido/<int:id_pedido>', views.editar_pedido, name='editar-pedido'),
    path('cadastrar/itens_pedido/<int:id_pedido>', views.cadastrar_itens_pedido, name='cadastrar-itens-pedido'),
    path('pedidos/retorna_informacoes_itens_pedido/<int:id_pedido>', views.retorna_informacoes_itens_pedido, name='retorna-informacoes-itens-pedido'),
    path('editar/itens_pedido/<int:id_pedido>', views.editar_itens_pedido, name='editar-itens-pedido'),
    path('remover/pedido/<int:id_pedido>', views.excluir_pedido, name='excluir-pedido'),
    path('gerar-pdf/pedido/<int:id_pedido>', views.gerar_pdf_pedido, name='gerar-pdf-pedido'),
    path('tendencias', views.acompanhamentos, name='acompanhamentos'),
    path('tendencias/cadastrar', views.cadastrar_acompanhamento, name='cadastrar-acompanhamento'),
    path('editar/tendencia/<int:id_acompanhamento>', views.editar_acompanhamento, name='editar-acompanhamento'),
    path('excluir/tendencia/<int:id_acompanhamento>', views.excluir_acompanhamento, name='excluir-acompanhamento'),
    path('prospecoes-clientes', views.prospeccoes_clientes, name="prospeccoes-clientes"),
    path('clientes-sem-pedido', views.clientes_sem_pedido, name="clientes-sem-pedido"),
    path('cancelamentos-pedidos-por-cliente', views.cancelamento_pedidos_por_cliente, name="cancelamentos-pedidos-clientes"),
    path('tarefas', views.listar_tarefas, name='tarefas'),
    path('tarefas/cadastrar', views.cadastrar_tarefa, name='cadastrar-tarefa'),
    path('editar/tarefa/<int:id_tarefa>', views.editar_tarefa, name="editar-tarefa"),
    path('excluir/tarefa<int:id_tarefa>', views.excluir_tarefa, name="excluir-tarefa"),
    path('configuracoes/pedidos', views.configuracoes_pedidos, name="configuracoes-pedidos"),
]

urlpatterns += customizacoes_urls

oli2/representacao/models/empresas.py
from .usuarios import Usuarios
from django.db import models
from django.conf import settings

class TiposEmpresa(models.Model):
    id_tipo_empresa = models.AutoField(primary_key=True)
    tipo = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.tipo


class MinhaEmpresa(models.Model):
    TIPO_IE_CHOICES = (
        ('CONTRIBUINTE', 'CONTRIBUINTE'),
        ('NAO CONTRIBUINTE', 'NÃO CONTRIBUINTE'),
        ('ISENTO', 'ISENTO'),
    )

    id_minha_empresa = models.AutoField(primary_key=True)
    logo = models.ImageField(null=True, blank=True, upload_to='minha-empresa/')
    razao_social = models.CharField(max_length=255, null=True, db_index=True)
    nome_fantasia = models.CharField(max_length=255, null=True, blank=True, db_index=True)
    cnpj = models.CharField(max_length=25, null=True, blank=True, db_index=True)
    tipo_ie = models.CharField(max_length=30, choices=TIPO_IE_CHOICES, null=True)
    inscricao_estadual = models.CharField(max_length=50, null=True, blank=True, db_index=True)
    telefone = models.CharField(max_length=80, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    email_nfe = models.EmailField(null=True, blank=True)
    endereco = models.CharField(max_length=80, null=True, blank=True)
    numero = models.IntegerField(null=True, blank=True)
    complemento = models.CharField(max_length=50, null=True, blank=True)
    bairro = models.CharField(max_length=80, null=True, blank=True)
    cep = models.CharField(max_length=20, null=True, blank=True)
    cidade = models.CharField(max_length=150, null=True, blank=True)
    uf = models.CharField(max_length=2, null=True, blank=True)


class Empresas(models.Model):
    TIPO_IE_CHOICES = (
        ('CONTRIBUINTE', 'CONTRIBUINTE'),
        ('NAO CONTRIBUINTE', 'NÃO CONTRIBUINTE'),
        ('ISENTO', 'ISENTO'),
    )

    id_empresa = models.AutoField(primary_key=True)
    logo = models.ImageField(null=True, blank=True, upload_to='empresas/')
    razao_social = models.CharField(max_length=255, null=True, db_index=True)
    nome_fantasia = models.CharField(max_length=255, null=True, blank=True, db_index=True)
    cnpj = models.CharField(max_length=25, null=True, blank=True, db_index=True)
    tipo_ie = models.CharField(max_length=30, choices=TIPO_IE_CHOICES, null=True)
    inscricao_estadual = models.CharField(max_length=50, null=True, blank=True, db_index=True)
    telefone = models.CharField(max_length=80, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    email_nfe = models.EmailField(null=True, blank=True)
    endereco = models.CharField(max_length=80, null=True, blank=True)
    numero = models.IntegerField(null=True, blank=True)
    complemento = models.CharField(max_length=50, null=True, blank=True)
    bairro = models.CharField(max_length=80, null=True, blank=True)
    cep = models.CharField(max_length=20, null=True, blank=True)
    cidade = models.CharField(max_length=150, null=True, blank=True)
    uf = models.CharField(max_length=2, null=True, blank=True)
    possui_pedido_minimo = models.BooleanField()
    pedido_minimo = models.FloatField(null=True, blank=True)
    possui_horario_pedido = models.BooleanField()
    horario_pedido = models.TimeField(null=True, blank=True)
    comissao = models.DecimalField(default=0, null=True, blank=True, max_digits=5, decimal_places=2)
    banco_empresa = models.CharField(max_length=15, null=True, blank=True)
    agencia_empresa = models.CharField(max_length=30, null=True, blank=True)
    conta_empresa = models.CharField(max_length=30, null=True, blank=True)
    id_tipo_empresa = models.ForeignKey(TiposEmpresa, on_delete=models.PROTECT)
    observacao = models.TextField(null=True, blank=True)

    def __str__(self):
        if self.nome_fantasia:
            return self.nome_fantasia
        else:
            return ''


class Clientes(models.Model):
    TIPO_IE_CHOICES = (
        ('CONTRIBUINTE', 'CONTRIBUINTE'),
        ('NAO CONTRIBUINTE', 'NÃO CONTRIBUINTE'),
        ('ISENTO', 'ISENTO'),
    )

    id_cliente = models.AutoField(primary_key=True)
    logo = models.ImageField(null=True, blank=True, upload_to='clientes/')
    razao_social = models.CharField(max_length=255, null=True, db_index=True)
    nome_fantasia = models.CharField(max_length=255, null=True, blank=True, db_index=True)
    cnpj = models.CharField(max_length=25, db_index=True)
    tipo_ie = models.TextField(max_length=30, choices=TIPO_IE_CHOICES, null=True, blank=True)
    inscricao_estadual = models.CharField(max_length=50, null=True, blank=True, db_index=True)
    telefone = models.CharField(max_length=80, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    email_nfe = models.EmailField(null=True, blank=True)
    endereco = models.CharField(max_length=80, null=True, blank=True)
    numero = models.IntegerField(null=True, blank=True)
    complemento = models.CharField(max_length=50, null=True, blank=True)
    bairro = models.CharField(max_length=80, null=True, blank=True)
    cep = models.CharField(max_length=20, null=True, blank=True)
    cidade = models.CharField(max_length=150, null=True, blank=True)
    uf = models.CharField(max_length=2, null=True, blank=True)
    banco_cliente = models.CharField(max_length=15, null=True, blank=True)
    agencia_cliente = models.CharField(max_length=30, null=True, blank=True)
    conta_cliente = models.CharField(max_length=30, null=True, blank=True)
    id_usuario = models.ForeignKey(Usuarios, on_delete=models.PROTECT, null=True, blank=True)
    prospectado_por_usuario = models.BooleanField()

    def __str__(self):
        if self.nome_fantasia:
            return self.nome_fantasia
        else:
            return ''

oli2/representacao/models/pessoas.py
from .usuarios import Usuarios
from .empresas import Empresas, Clientes
from django.db import models


class Prepostos(models.Model):
    id_preposto = models.AutoField(primary_key=True)
    possui_vinculo_empresa = models.BooleanField()
    comissao = models.DecimalField(null=True, blank=True, max_digits=5, decimal_places=2)
    id_usuario = models.ForeignKey(Usuarios, on_delete=models.PROTECT, null=True)
    empresa = models.ManyToManyField(Empresas, null=True, blank=True)

    def __str__(self):
        return self.id_usuario.nome


class Rotas(models.Model):
    id_rota = models.AutoField(primary_key=True)
    nome_rota = models.CharField(max_length=300)


class RotaPrepostos(models.Model):
    id_rota_preposto = models.AutoField(primary_key=True)
    id_rota = models.ForeignKey(Rotas, on_delete=models.CASCADE)
    id_preposto = models.ForeignKey(Prepostos, on_delete=models.PROTECT)


class PrepostoClientes(models.Model):
    FREQUENCIA = (
        ('SEMANAL', 'SEMANAL'),
        ('QUINZENAL', 'QUINZENAL'),
        ('MENSAL', 'MENSAL'),
        ('OUTRA', 'OUTRA')
    )

    id_rota_preposto = models.ForeignKey(RotaPrepostos, on_delete=models.CASCADE)
    id_cliente = models.ForeignKey(Clientes, on_delete=models.PROTECT)
    s = models.BooleanField()
    t = models.BooleanField()
    q = models.BooleanField()
    qi = models.BooleanField()
    sx = models.BooleanField()
    sa = models.BooleanField()
    frequencia = models.CharField(max_length=30, choices=FREQUENCIA, null=True, blank=True)
    outra = models.IntegerField(null=True, blank=True)


class Contatos(models.Model):
    id_contato = models.AutoField(primary_key=True)
    nome_contato = models.CharField(max_length=255, null=True, db_index=True)
    possui_vinculo_empresa = models.BooleanField()
    possui_vinculo_cliente = models.BooleanField()
    telefone = models.CharField(max_length=80, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    cargo = models.CharField(max_length=255, null=True, blank=True)
    banco_contato = models.CharField(max_length=15, null=True, blank=True)
    agencia_contato = models.CharField(max_length=30, null=True, blank=True)
    conta_contato = models.CharField(max_length=30, null=True, blank=True)
    empresa = models.ManyToManyField(Empresas, null=True, blank=True)
    cliente = models.ManyToManyField(Clientes, null=True, blank=True)

    def __str__(self):
        return self.nome_contato

oli2/representacao/views/funcoes.py
from django.contrib import messages, auth

def mensagem_edicao_sucesso(request):
    messages.success(request, 'Atualizado com sucesso')


def mensagem_cadastro_sucesso(request):
    messages.success(request, 'Cadastro realizado com sucesso')

oli2/representacao/templates/pessoas/contato_form.html
{% extends 'partials/dashboard.html' %}
{% load widget_tweaks %}
{% block custom-css%}
{{ form.media.css }}
<style>
    input, select {width: 100%}
</style>
{% endblock %}
{% block content %}
<div class="container-fluid">
    <h1 class="h3 mb-4 text-gray-800">Cadastro de contatos</h1>
    <div>
        <form action="{{ request.path }}" method="post">
            <div class="form-row mb-2">
                {% include 'partials/submit.html' %}
            </div>
            <div class="form-row">
                <div class="form-group col-md-3">
                    <label>
                        {% render_field form.possui_vinculo_empresa %}
                        Possui vínculo com empresa
                    </label>
                </div>
                <div class="form-group col-md-3">
                    <label>
                        {% render_field form.possui_vinculo_cliente %}
                        Possui vínculo com cliente
                    </label>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label class="font-weight-bold">Nome</label>
                    {% render_field form.nome_contato class="form-control" placeholder="Ex: João" %}
                </div>
                <div class="form-group col-md-6">
                    <label class="font-weight-bold">Cargo</label>
                    {% render_field form.cargo class="form-control" placeholder="Ex: Diretor finaceiro" %}
                </div>
                 <div class="form-group col-md-6">
                     <label class="font-weight-bold">Telefone</label>
                     {% render_field form.telefone class="form-control" placeholder="Ex: (51) 99999-9999" %}
                </div>
                <div class="form-group col-md-6">
                    <label class="font-weight-bold">E-mail</label>
                    {% render_field form.email class="form-control" placeholder="joao@gmail.com" %}
                </div>
            </div>
            <div id="campo-empresas">
                <div class="form-group col-md-12 mb-2">
                    <label class="font-weight-bold">Empresa</label>
                    {% render_field form.empresa class="form-control" %}
                </div>
            </div>
            <div id="campo-clientes">
                <div class="form-group col-md-12">
                    <label class="font-weight-bold">Cliente</label>
                    {% render_field form.cliente class="form-control" %}
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}
{% block custom-scripts %}
{{ form.media.js }}
<script>
    let mostraEscondeCampoEmpresas = () => {
        let possuiVinculoEmpresa = $("#id_possui_vinculo_empresa").is(":checked");

        if(possuiVinculoEmpresa){
            $("#campo-empresas")
                .removeClass("d-none")
                .addClass("form-row");
        }
        else{
            $("#campo-empresas")
                .removeClass("form-row")
                .addClass("d-none");
        }
    }

    let mostraEscondeCampoClientes = () => {
        let possuiVinculoCliente = $("#id_possui_vinculo_cliente").is(":checked");

        if(possuiVinculoCliente){
            $("#campo-clientes")
                .removeClass("d-none")
                .addClass("form-row");
        }
        else{
            $("#campo-clientes")
                .removeClass("form-row")
                .addClass("d-none");
        }
    }

    let init = () => {
        mostraEscondeCampoEmpresas();
        mostraEscondeCampoClientes();
    }

    $(document).ready(function(){
        init();

        $("#id_possui_vinculo_empresa").change(function(){
            mostraEscondeCampoEmpresas();
        });

        $("#id_possui_vinculo_cliente").change(function(){
            mostraEscondeCampoClientes();
        });
    });
</script>
{% endblock %}

oli2/representacao/templates/pessoas/edicao_rotas_prepostos_form.html
{% extends 'partials/dashboard.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container-fluid">
    <h1 class="h3 mb-4 text-gray-800">Cadastro de rotas dos prepostos</h1>
    <div>
        <form action="{{ request.path }}" method="post">
            {% include 'partials/submit.html' %}
             <div class="form-row mt-3">
                 <div class="form-group col-md-12">
                     <label class="font-weight-bold">Nome ou código da rota</label>
                     {% render_field form.nome_rota class="form-control" placeholder="Ex: Rota 1"%}
                 </div>
                 <div class="form-group col-md-12">
                     <label class="font-weight-bold">Prepostos</label>
                     {% render_field form.prepostos id="prepostos-rota" class="form-control" %}
                 </div>
            </div>
            <div class="form-row">
                 <div class="form-group col-md-5">
                    <button type="button" id="adiciona-preposto-rota" class="btn btn-dark font-weight-bold">Adicionar Preposto</button>
                 </div>
            </div>
            <div id="prepostos" class="form-row">
            </div>
        </form>
    </div>
</div>
{% endblock %}
{% block custom-scripts %}
    {% include 'pessoas/rotas_prepostos_js.html'%}
    <script>
        $(document).ready(function() {
          $.ajax({
            type: "POST",
            url: "{% url 'retorna-informacoes-rota-prepostos' id_rota %}",
            contentType: 'application/json',
            async: false,
            success: function(data){
                prepostos = data.rota_prepostos_clientes.prepostos;
            },
            error: function(data){
                console.log(data);
            }
          });

          atualizaExibePrepostos();
        });
    </script>
{% endblock %}

oli2/representacao/templates/pessoas/preposto_form.html
{% extends 'partials/dashboard.html' %}
{% load widget_tweaks %}
{% block custom-css%}
{{ form.media.css }}
<style>
    input, select {width: 100%}
</style>
{% endblock %}
{% block content %}
<div class="container-fluid">
    <h1 class="h3 mb-4 text-gray-800">Cadastro de prepostos</h1>
    <div>
        <form action="{{ request.path }}" method="post">
            <div class="form-row mb-2">
                {% include 'partials/submit.html' %}
            </div>
            <div class="form-row">
                <div class="form-group col-md-3">
                    <label>
                        {% render_field form.possui_vinculo_empresa %}
                        Possui vínculo com empresa
                    </label>
                </div>
            </div>
            <div class="form-row">
                {% render_field form.id_usuario %}
            </div>
            <div class="form-row">
                 <div class="form-group col-md-6">
                     <label class="font-weight-bold">Nome</label>
                     <input type="text" name="nome" maxlength="255" class="form-control" value="{{ preposto.id_usuario.nome }}" id="id_nome" disabled>
                </div>
                 <div class="form-group col-md-6">
                     <label class="font-weight-bold">Telefone</label>
                     <input type="text" name="telefone" maxlength="80" class="form-control" value="{{ preposto.id_usuario.telefone }}" id="id_telefone" disabled>
                </div>
                <div class="form-group col-md-6">
                    <label class="font-weight-bold">E-mail</label>
                    <input type="email" name="email" maxlength="254" class="form-control" value="{{ preposto.id_usuario.email }}" id="id_email" disabled>
                </div>
                <div class="form-group col-md-6">
                    <label class="font-weight-bold">Comissão</label>
                    {% render_field form.comissao class="form-control" placeholder="Ex: 2" %}
                </div>
            </div>
            <div id="campo-empresas">
                <div class="form-group col-md-12 mb-2">
                    <label class="font-weight-bold">Empresa</label>
                    {% render_field form.empresa class="form-control" %}
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}
{% block custom-scripts %}
{{ form.media.js }}
<script>
    let mostraEscondeCampoEmpresas = () => {
        let possuiVinculoEmpresa = $("#id_possui_vinculo_empresa").is(":checked");

        if(possuiVinculoEmpresa){
            $("#campo-empresas")
                .removeClass("d-none")
                .addClass("form-row");
        }
        else{
            $("#campo-empresas")
                .removeClass("form-row")
                .addClass("d-none");
        }
    }

    let init = () => {
        mostraEscondeCampoEmpresas();
    }

    $(document).ready(function(){
        init();

        $("#id_possui_vinculo_empresa").change(function(){
            mostraEscondeCampoEmpresas();
        });
    });
</script>
{% endblock %}

oli2/representacao/templates/pessoas/rotas_prepostos_form.html
{% extends 'partials/dashboard.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container-fluid">
    <h1 class="h3 mb-4 text-gray-800">Cadastro de rotas dos prepostos</h1>
    <div>
        <form action="{{ request.path }}" method="post">
            {% include 'partials/submit.html' %}
             <div class="form-row mt-3">
                 <div class="form-group col-md-12">
                     <label class="font-weight-bold">Nome ou código da rota</label>
                 </div>
                 <div class="form-group col-md-12">
                    <label class="font-weight-bold">Prepostos</label>
                    <select id="preposto-rota" class="form-control">
                        <option value="0">---------</option>
                        {% for preposto in prepostos%}
                            <option value="{{preposto.id_preposto}}">
                                {{preposto.id_usuario.nome}}
                            </option>
                        {% endfor %}
                    </select>
                 </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}