oli2/api/urls.py
from api.views.configuracoes import *
from api.views.empresas import *
from api.views.pessoas import *
from api.views.pedidos import *
from api.views.usuarios import *
from api.views.relatorios import *
from api.views.produtos import *
from rest_framework import routers

router = routers.DefaultRouter()
router.register('configuracoes', ConfiguracoesViewSet, 'Configuracoes')
router.register('empresas', EmpresasViewSet, 'Empresas')
router.register('minha_empresa', MinhaEmpresaViewSet, 'MinhaEmpresa')
router.register('tipos_empresa', TiposEmpresaViewSet, 'TiposEmpresa')
router.register('clientes', ClientesViewSet, 'Clientes')
router.register('prepostos', PrepostosViewSet, 'Prepostos')
router.register('rotas', RotasViewSet, 'Rotas')
router.register('rotas_prepostos', RotasPrepostosViewSet, 'RotasPrepostos')
router.register('preposto_clientes', PrepostoClientesViewSet, 'PrepostoClientes')
router.register('contatos', ContatosViewSet, 'Contatos')
router.register('formas_pagamento', FormasPagamentoViewSet, 'FormasPagamento')
router.register('pedidos', PedidosViewSet, 'Pedidos')
router.register('itens_pedido', ItensPedidoViewSet, 'ItensPedido')
router.register('categorias', CategoriasViewSet, 'Categorias')
router.register('unidades_venda', UnidadesVendaViewSet, 'UnidadesVenda')
router.register('tipos_embalagem', TiposEmbalagemViewSet, 'TiposEmbalagem')
router.register('produtos', ProdutosViewSet, 'Produtos')
router.register('acompanhamentos', AcompanhamentosViewSet, 'Acompanhamentos')
router.register('acompanhamento_empresa', AcompanhamentoEmpresaViewSet, 'AcompanhamentoEmpresa')
router.register('acompanhamento_preposto_empresa', AcompanhamentoPrepostoEmpresaViewSet, 'AcompanhamentoPrepostoEmpresa')
router.register('usuarios', UsuariosViewSet, 'Usuarios')
router.register('tarefas', TarefasViewSet, 'Tarefas')

urlpatterns = router.urls

oli2/representacao/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .customizacoes_urls import urlpatterns as customizacoes_urls
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login', auth_views.LoginView.as_view(template_name='usuarios/login.html'), name='login'),
    path('autenticar', views.autenticar, name='autenticar'),
    path('logout', auth_views.LogoutView.as_view(template_name='usuarios/logout.html'), name='logout'),
    path('usuarios/', views.listar_usuarios, name='usuarios'),
    path('usuarios/cadastrar', views.cadastrar_usuario, name='cadastrar-usuario'),
    path('editar/usuario/<int:id_usuario>', views.editar_usuario, name='editar-usuario'),
    path('remover/usuario/<int:id_usuario>', views.excluir_usuario, name='excluir-usuario'),
    path('tipos-empresa/', views.listar_tipos_empresa, name='tipos-empresa'),
    path('tipos-empresa/cadastrar', views.cadastrar_tipo_empresa, name='cadastrar-tipo-empresa'),
    path('editar/tipo_empresa/<int:id_tipo_empresa>', views.editar_tipo_empresa, name='editar-tipo-empresa'),
    path('remover/tipo_empresa/<int:id_tipo_empresa>', views.excluir_tipo_empresa, name='excluir-tipo-empresa'),
    path('minha_empresa/cadastrar', views.cadastrar_minha_empresa, name='cadastrar-minha-empresa'),
    path('editar/minha_empresa/<int:id_minha_empresa>', views.editar_minha_empresa, name='editar-minha-empresa'),
    path('empresas', views.listar_empresas, name='empresas'),
    path('empresas/cadastrar', views.cadastrar_empresa, name='cadastrar-empresa'),
    path('editar/empresa/<int:id_empresa>', views.editar_empresa, name='editar-empresa'),
    path('excluir/empresa/<int:id_empresa>', views.excluir_empresa, name='excluir-empresa'),
    path('clientes/', views.listar_clientes, name='clientes'),
    path('buscar/cliente', views.buscar_dados_clientes, name='buscar-cliente'),
    path('clientes/cadastrar', views.cadastrar_cliente, name='cadastrar-cliente'),
    path('editar/cliente/<int:id_cliente>', views.editar_cliente, name='editar-cliente'),
    path('excluir/cliente/<int:id_cliente>', views.excluir_cliente, name='excluir-cliente'),
    path('prepostos/', views.listar_prepostos, name='prepostos'),
    path('prepostos/cadastrar/', views.cadastrar_preposto, name='cadastrar-preposto'),
    path('editar/preposto/<int:id_preposto>', views.editar_preposto, name='editar-preposto'),
    path('remover/preposto/<int:id_preposto>', views.excluir_preposto, name='excluir-preposto'),
    path('rotas-prepostos', views.listar_rotas_prepostos, name='rotas-prepostos'),
    path('rotas-prepostos/retorna_informacoes_preposto', views.retorna_informacoes_preposto, name='retorna-informacoes-preposto'),
    path('rotas-prepostos/cadastrar', views.cadastrar_rotas_prepostos, name='cadastrar-rotas-prepostos'),
    path('rotas-prepostos/retorna_informacoes_rota_prepostos/<int:id_rota>', views.retorna_informacoes_rota_prepostos, name='retorna-informacoes-rota-prepostos'),
    path('editar/rota/<int:id_rota>', views.editar_rotas_prepostos, name='editar-rota'),
    path('remover/rota/<int:id_rota>', views.excluir_rota, name='excluir-rota'),
    path('contatos', views.listar_contatos, name='contatos'),
    path('contatos/cadastrar', views.cadastrar_contato, name='cadastrar-contato'),
    path('editar/contato/<int:id_contato>', views.editar_contato, name='editar-contato'),
    path('remover/contato/<int:id_contato>', views.excluir_contato, name='excluir-contato'),
    path('categorias/', views.listar_categorias, name='categorias'),
    path('categorias/cadastrar', views.cadastrar_categoria, name='cadastrar-categoria'),
    path('editar/categoria/<int:id_categoria>', views.editar_categoria, name='editar-categoria'),
    path('remover/categoria/<int:id_categoria>', views.excluir_categoria, name='excluir-categoria'),
    path('unidades-venda/', views.listar_unidades_venda, name='unidades-venda'),
    path('unidades-venda/cadastrar', views.cadastrar_unidade_venda, name='cadastrar-unidade-venda'),
    path('editar/unidade_venda/<int:id_unidade_venda>', views.editar_unidade_venda, name='editar-unidade-venda'),
    path('remover/unidade_venda/<int:id_unidade_venda>', views.excluir_unidade_venda, name='excluir-unidade-venda'),
    path('tipos-embalagem/', views.listar_tipos_embalagem, name='tipos-embalagem'),
    path('tipos-embalagem/cadastrar', views.cadastrar_tipo_embalagem, name='cadastrar-tipo-embalagem'),
    path('editar/tipo_embalagem/<int:id_tipo_embalagem>', views.editar_tipo_embalagem, name='editar-tipo-embalagem'),
    path('remover/tipo_embalagem/<int:id_tipo_embalagem>', views.excluir_tipo_embalagem, name='excluir-tipo-embalagem'),
    path('produtos', views.listar_produtos, name='produtos'),
    path('produtos/cadastrar', views.cadastrar_produto, name='cadastrar-produto'),
    path('editar/produto/<int:id_produto>', views.editar_produto, name='editar-produto'),
    path('remover/produto/<int:id_produto>', views.excluir_produto, name='excluir-produto'),
    path('formas-pagamento/', views.listar_formas_pagamento, name='formas-pagamento'),
    path('formas-pagamento/cadastrar', views.cadastrar_forma_pagamento, name='cadastrar-forma-pagamento'),
    path('editar/forma_pagamento/<int:id_forma_pagamento>', views.editar_forma_pagamento, name='editar-forma-pagamento'),
    path('remover/forma_pagamento/<int:id_forma_pagamento>', views.excluir_forma_pagamento, name='excluir-forma-pagamento'),
    path('pedidos/', views.listar_pedidos, name='pedidos'),
    path('pedidos/cadastrar', views.cadastrar_pedido, name='cadastrar-pedido'),
    path('pedidos/confirmar_itens_pedido/<int:id_pedido>', views.confirmar_itens_pedido, name='confirmar-itens-pedido'),
    path('editar/pedido/<int:id_pedido>', views.editar_pedido, name='editar-pedido'),
    path('cadastrar/itens_pedido/<int:id_pedido>', views.cadastrar_itens_pedido, name='cadastrar-itens-pedido'),
    path('pedidos/retorna_informacoes_itens_pedido/<int:id_pedido>', views.retorna_informacoes_itens_pedido, name='retorna-informacoes-itens-pedido'),
    path('editar/itens_pedido/<int:id_pedido>', views.editar_itens_pedido, name='editar-itens-pedido'),
    path('remover/pedido/<int:id_pedido>', views.excluir_pedido, name='excluir-pedido'),
    path('gerar-pdf/pedido/<int:id_pedido>', views.gerar_pdf_pedido, name='gerar-pdf-pedido'),
    path('tendencias', views.acompanhamentos, name='acompanhamentos'),
    path('tendencias/cadastrar', views.cadastrar_acompanhamento, name='cadastrar-acompanhamento'),
    path('editar/tendencia/<int:id_acompanhamento>', views.editar_acompanhamento, name='editar-acompanhamento'),
    path('excluir/tendencia/<int:id_acompanhamento>', views.excluir_acompanhamento, name='excluir-acompanhamento'),
    path('prospecoes-clientes', views.prospeccoes_clientes, name="prospeccoes-clientes"),
    path('clientes-sem-pedido', views.clientes_sem_pedido, name="clientes-sem-pedido"),
    path('cancelamentos-pedidos-por-cliente', views.cancelamento_pedidos_por_cliente, name="cancelamentos-pedidos-clientes"),
    path('tarefas', views.listar_tarefas, name='tarefas'),
    path('tarefas/cadastrar', views.cadastrar_tarefa, name='cadastrar-tarefa'),
    path('editar/tarefa/<int:id_tarefa>', views.editar_tarefa, name="editar-tarefa"),
    path('excluir/tarefa<int:id_tarefa>', views.excluir_tarefa, name="excluir-tarefa"),
    path('configuracoes/pedidos', views.configuracoes_pedidos, name="configuracoes-pedidos"),
]

urlpatterns += customizacoes_urls

oli2/representacao/models/configuracoes.py
from django.db import models

class Configuracoes(models.Model):
    id_configuracoes = models.AutoField(primary_key=True)
    codigo = models.CharField(max_length=100)
    descricao = models.TextField()
    valor = models.CharField(max_length=255)

    def __str__(self):
        return self.codigo

oli2/representacao/models/empresas.py
from .usuarios import Usuarios
from django.db import models
from django.conf import settings

class TiposEmpresa(models.Model):
    id_tipo_empresa = models.AutoField(primary_key=True)
    tipo = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.tipo


class MinhaEmpresa(models.Model):
    TIPO_IE_CHOICES = (
        ('CONTRIBUINTE', 'CONTRIBUINTE'),
        ('NAO CONTRIBUINTE', 'NÃO CONTRIBUINTE'),
        ('ISENTO', 'ISENTO'),
    )

    id_minha_empresa = models.AutoField(primary_key=True)
    logo = models.ImageField(null=True, blank=True, upload_to='minha-empresa/')
    razao_social = models.CharField(max_length=255, null=True, db_index=True)
    nome_fantasia = models.CharField(max_length=255, null=True, blank=True, db_index=True)
    cnpj = models.CharField(max_length=25, null=True, blank=True, db_index=True)
    tipo_ie = models.CharField(max_length=30, choices=TIPO_IE_CHOICES, null=True)
    inscricao_estadual = models.CharField(max_length=50, null=True, blank=True, db_index=True)
    telefone = models.CharField(max_length=80, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    email_nfe = models.EmailField(null=True, blank=True)
    endereco = models.CharField(max_length=80, null=True, blank=True)
    numero = models.IntegerField(null=True, blank=True)
    complemento = models.CharField(max_length=50, null=True, blank=True)
    bairro = models.CharField(max_length=80, null=True, blank=True)
    cep = models.CharField(max_length=20, null=True, blank=True)
    cidade = models.CharField(max_length=150, null=True, blank=True)
    uf = models.CharField(max_length=2, null=True, blank=True)


class Empresas(models.Model):
    TIPO_IE_CHOICES = (
        ('CONTRIBUINTE', 'CONTRIBUINTE'),
        ('NAO CONTRIBUINTE', 'NÃO CONTRIBUINTE'),
        ('ISENTO', 'ISENTO'),
    )

    id_empresa = models.AutoField(primary_key=True)
    logo = models.ImageField(null=True, blank=True, upload_to='empresas/')
    razao_social = models.CharField(max_length=255, null=True, db_index=True)
    nome_fantasia = models.CharField(max_length=255, null=True, blank=True, db_index=True)
    cnpj = models.CharField(max_length=25, null=True, blank=True, db_index=True)
    tipo_ie = models.CharField(max_length=30, choices=TIPO_IE_CHOICES, null=True)
    inscricao_estadual = models.CharField(max_length=50, null=True, blank=True, db_index=True)
    telefone = models.CharField(max_length=80, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    email_nfe = models.EmailField(null=True, blank=True)
    endereco = models.CharField(max_length=80, null=True, blank=True)
    numero = models.IntegerField(null=True, blank=True)
    complemento = models.CharField(max_length=50, null=True, blank=True)
    bairro = models.CharField(max_length=80, null=True, blank=True)
    cep = models.CharField(max_length=20, null=True, blank=True)
    cidade = models.CharField(max_length=150, null=True, blank=True)
    uf = models.CharField(max_length=2, null=True, blank=True)
    possui_pedido_minimo = models.BooleanField()
    pedido_minimo = models.FloatField(null=True, blank=True)
    possui_horario_pedido = models.BooleanField()
    horario_pedido = models.TimeField(null=True, blank=True)
    comissao = models.DecimalField(default=0, null=True, blank=True, max_digits=5, decimal_places=2)
    banco_empresa = models.CharField(max_length=15, null=True, blank=True)
    agencia_empresa = models.CharField(max_length=30, null=True, blank=True)
    conta_empresa = models.CharField(max_length=30, null=True, blank=True)
    id_tipo_empresa = models.ForeignKey(TiposEmpresa, on_delete=models.PROTECT)
    observacao = models.TextField(null=True, blank=True)

    def __str__(self):
        if self.nome_fantasia:
            return self.nome_fantasia
        else:
            return ''


class Clientes(models.Model):
    TIPO_IE_CHOICES = (
        ('CONTRIBUINTE', 'CONTRIBUINTE'),
        ('NAO CONTRIBUINTE', 'NÃO CONTRIBUINTE'),
        ('ISENTO', 'ISENTO'),
    )

    id_cliente = models.AutoField(primary_key=True)
    logo = models.ImageField(null=True, blank=True, upload_to='clientes/')
    razao_social = models.CharField(max_length=255, null=True, db_index=True)
    nome_fantasia = models.CharField(max_length=255, null=True, blank=True, db_index=True)
    cnpj = models.CharField(max_length=25, db_index=True)
    tipo_ie = models.TextField(max_length=30, choices=TIPO_IE_CHOICES, null=True, blank=True)
    inscricao_estadual = models.CharField(max_length=50, null=True, blank=True, db_index=True)
    telefone = models.CharField(max_length=80, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    email_nfe = models.EmailField(null=True, blank=True)
    endereco = models.CharField(max_length=80, null=True, blank=True)
    numero = models.IntegerField(null=True, blank=True)
    complemento = models.CharField(max_length=50, null=True, blank=True)
    bairro = models.CharField(max_length=80, null=True, blank=True)
    cep = models.CharField(max_length=20, null=True, blank=True)
    cidade = models.CharField(max_length=150, null=True, blank=True)
    uf = models.CharField(max_length=2, null=True, blank=True)
    banco_cliente = models.CharField(max_length=15, null=True, blank=True)
    agencia_cliente = models.CharField(max_length=30, null=True, blank=True)
    conta_cliente = models.CharField(max_length=30, null=True, blank=True)
    id_usuario = models.ForeignKey(Usuarios, on_delete=models.PROTECT, null=True, blank=True)
    prospectado_por_usuario = models.BooleanField()

    def __str__(self):
        if self.nome_fantasia:
            return self.nome_fantasia
        else:
            return ''

oli2/representacao/forms/configuracoes.py
from ..models import *
from django import forms
from django.forms import ModelForm

class ConfiguracoesForm(forms.Form):
    pe01 = forms.BooleanField(required=False)
    pe02 = forms.CharField(max_length=100)
    cg01 = forms.BooleanField(required=False)

oli2/api/views/empresas.py
from rest_framework import viewsets
from representacao.models import *
from api.serializers import *


class EmpresasViewSet(viewsets.ModelViewSet):
    queryset = Empresas.objects.all()
    serializer_class = EmpresasSerializer


class MinhaEmpresaViewSet(viewsets.ModelViewSet):
    queryset = MinhaEmpresa.objects.all()
    serializer_class = MinhaEmpresaSerializer


class TiposEmpresaViewSet(viewsets.ModelViewSet):
    queryset = TiposEmpresa.objects.all()
    serializer_class = TiposEmpresaSerializer


class ClientesViewSet(viewsets.ModelViewSet):
    queryset = Clientes.objects.all()
    serializer_class = ClientesSerializer

oli2/representacao/views/configuracoes.py
import distutils
from ..models import *
from ..forms import *
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from .funcoes import *

@login_required
def configuracoes_pedidos(request, template_name='configuracoes/configuracoes_pedidos.html'):
    pe01 = get_object_or_404(Configuracoes, pk=1)
    pe02 = get_object_or_404(Configuracoes, pk=2)

    if request.method == "POST":
        form = ConfiguracoesForm(request.POST)
        if form.is_valid():
            pe01.valor = form.cleaned_data['pe01']
            pe01.save()
            pe02.valor = form.cleaned_data['pe02']
            pe02.save()

    else:
        form = ConfiguracoesForm()
        form.fields['pe01'].initial = eval(pe01.valor)
        form.fields['pe02'].initial = pe02.valor

    return render(request, template_name, {'form': form, 'pe01': pe01, 'pe02': pe02})

oli2/representacao/views/funcoes.py
from django.contrib import messages, auth

def mensagem_edicao_sucesso(request):
    messages.success(request, 'Atualizado com sucesso')


def mensagem_cadastro_sucesso(request):
    messages.success(request, 'Cadastro realizado com sucesso')

oli2/representacao/templates/empresas/empresa_form.html
{% extends 'partials/dashboard.html' %}
{% load widget_tweaks %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <h1 class="h3 mb-4 text-gray-800">Cadastro de empresas</h1>
    <div>
        <form action="{{ request.path }}" method="post" enctype='multipart/form-data' >
            {% include 'partials/submit.html' %}
            <div class="form-row">
                <div class="form-group col-md-3">
                    <label>
                        {% render_field form.possui_pedido_minimo %}
                        Possui pedido mínimo
                    </label>
                </div>
                <div class="form-group col-md-4">
                    <label>
                        {% render_field form.possui_horario_pedido %}
                        Possui horário pedido
                    </label>
                </div>
            </div>
            <div id="imagem-selecionada">
                {% if form.instance.logo  %}
                    <img width="200" src="{{ form.instance.logo.url }}">
                {% endif %}
            </div>
            <div class="form-row mt-4 mb-3">
                <div class="form-group col-md-12">
                    <label class="font-weight-bold">Logo</label>
                    <div class="imagem">
                        {% render_field form.logo %}
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4">
                    <label class="font-weight-bold">Razão social</label>
                    {% render_field form.razao_social class="form-control" placeholder="Ex: Ryan e Eduardo Entregas Expressas ME" %}
                </div>
                <div class="form-group col-md-5">
                    <label class="font-weight-bold">Nome fantasia</label>
                    {% render_field form.nome_fantasia class="form-control" placeholder="Ex: R&E Entregas Expressas" %}
                </div>
                <div class="form-group col-md-3">
                    <label class="font-weight-bold">CNPJ</label>
                    {% render_field form.cnpj class="form-control" placeholder="Ex: 90.848.337/0001-46" %}
                </div>
                <div class="form-group col-md-2">
                    <label class="font-weight-bold">Contribuinte</label>
                    {% render_field form.tipo_ie class="form-control" %}
                </div>
                <div class="form-group col-md-3">
                    <label class="font-weight-bold">Inscrição estadual</label>
                    {% render_field form.inscricao_estadual class="form-control" placeholder="Ex: 400.338.194.266"%}
                </div>
                <div class="form-group col-md-4">
                    <label class="font-weight-bold">Endereço</label>
                    {% render_field form.endereco class="form-control" placeholder="Ex: Rua Gibraltar" %}
                </div>
                <div class="form-group col-md-3">
                    <label class="font-weight-bold">Numero</label>
                    {% render_field form.numero class="form-control" placeholder="Ex: 535" %}
                </div>
                <div class="form-group col-md-2">
                    <label class="font-weight-bold">Complemento</label>
                    {% render_field form.complemento class="form-control" placeholder="Ex: Sala 1" %}
                </div>
                <div class="form-group col-md-3">
                    <label class="font-weight-bold">Bairro</label>
                    {% render_field form.bairro class="form-control" placeholder="Ex: Santo Amaro" %}
                </div>
                <div class="form-group col-md-3">
                    <label class="font-weight-bold">Cidade</label>
                    {% render_field form.cidade class="form-control" placeholder="Ex: São Paulo" %}
                </div>
                <div class="form-group col-md-3">
                    <label class="font-weight-bold">CEP</label>
                    {% render_field form.cep class="form-control" placeholder="Ex: 04755-070"%}
                </div>
                <div class="form-group col-md-1">
                    <label class="font-weight-bold">UF</label>
                    {% render_field form.uf class="form-control" placeholder="Ex: SP" %}
                </div>
                <div class="form-group col-md-4">
                    <label class="font-weight-bold">Tipo de empresa</label>
                    {% render_field form.id_tipo_empresa class="form-control" %}
                </div>
                <div class="form-group col-md-4">
                    <label class="font-weight-bold">Comissão</label>
                    {% render_field form.comissao class="form-control" placeholder="Ex: 10"%}
                </div>
                <div class="form-group col-md-4">
                    <label class="font-weight-bold">Telefone</label>
                    {% render_field form.telefone class="form-control" placeholder="Ex: (11) 3750-9740" %}
                </div>
                <div class="form-group col-md-6">
                    <label class="font-weight-bold">E-mail</label>
                    {% render_field form.email class="form-control" placeholder="Ex: contato@reentregas.com.br" %}
                </div>
                <div class="form-group col-md-6">
                    <label class="font-weight-bold">E-mail NFE</label>
                    {% render_field form.email_nfe class="form-control" placeholder="Ex: nfe@reentregas.com.br" %}
                </div>
            </div>
            <div class="form-row">
                <div id="campo-pedido-minimo" class="d-none">
                    <label class="font-weight-bold">Pedido mínimo</label>
                    {% render_field form.pedido_minimo class="form-control" %}
                </div>
                <div id="campo-horario-pedido" class="d-none">
                    <label class="font-weight-bold">Horário pedido</label>
                    {% render_field form.horario_pedido class="form-control" %}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-12">
                    <label class="font-weight-bold">Observação</label>
                    {% render_field form.observacao class="form-control" %}
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}
{% block custom-scripts %}
<script>
    let mostraEscondeCampoPedidoMinimo = () => {
        let temPedidoMinimo = $("#id_possui_pedido_minimo").is(":checked");

        if(temPedidoMinimo){
            $("#campo-pedido-minimo")
                .removeClass("d-none")
                .addClass("form-group col-md-6");
        }
        else{
            $("#campo-pedido-minimo")
                .removeClass("form-group col-md-6")
                .addClass("d-none");
        }
    }

    let mostraEscondeCampoHorarioPedido = () => {
        let temHorarioPedido = $("#id_possui_horario_pedido").is(":checked");

        if(temHorarioPedido){
            $("#campo-horario-pedido")
                .removeClass("d-none")
                .addClass("form-group col-md-6");
        }
        else{
            $("#campo-horario-pedido")
                .removeClass("form-group col-md-6")
                .addClass("d-none");
        }
    }

    let init = () => {
        mostraEscondeCampoPedidoMinimo();
        mostraEscondeCampoHorarioPedido();
    }

    $(document).ready(function(){
        init();

        $("#id_possui_pedido_minimo").change(function(){
            mostraEscondeCampoPedidoMinimo();
        });

        $("#id_possui_horario_pedido").change(function(){
            mostraEscondeCampoHorarioPedido();
        });

        $("input[type=file]").on("change", function() {
            let fileName = $(this).val().split("\\").pop();

            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);

            mostraImagem();
        });
    });
</script>
{% endblock %}

oli2/representacao/templates/empresas/tipo_empresa_form.html
{% extends 'partials/dashboard.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container-fluid">
    <h1 class="h3 mb-4 text-gray-800">Cadastro de tipos de empresa</h1>
    <div>
        <form action="{{ request.path }}" method="post">
            {% include 'partials/submit.html' %}
            <div class="form-row mt-2">
                <div class="form-group col-md-5">
                    <label class="font-weight-bold">Tipo</label>
                    {% render_field form.tipo class="form-control" placeholder="Ex: Fornecedor" %}
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}